import { IWebtoon } from './types'
import { doc, setDoc } from 'firebase/firestore'
import { db } from '../../firebase'

export const WebtoonData: IWebtoon[] = [
  {
    webtoonId: 648419,
    title: '뷰티풀 군바리',
    author: '설이 / 윤성원',
    des: '"여자도 군대에 간다면?"본격 여자도 군대 가는 만화!',
    url: 'https://comic.naver.com/webtoon/list?titleId=648419&weekday=mon',
    img: 'https://image-comic.pstatic.net/webtoon/648419/thumbnail/thumbnail_IMAG21_d9398229-cbfd-47dc-9208-0a6fb936f3a7.jpg',
    service: 'naver',
    searchKeyword: '뷰티풀군바리설이/윤성원',
    genre: ['스토리', '드라마'],
    day: 'mon',
  },
  {
    webtoonId: 783052,
    title: '퀘스트지상주의',
    author: '박태준 만화회사',
    des: '[외모지상주의], [싸움독학], [인생존망]과 세계관을 공유하는 작품!',
    url: 'https://comic.naver.com/webtoon/list?titleId=783052&weekday=mon',
    img: 'https://image-comic.pstatic.net/webtoon/783052/thumbnail/thumbnail_IMAG21_e14cbea7-8416-40e7-9aae-ccff970ac88f.jpg',
    service: 'naver',
    searchKeyword: '퀘스트지상주의박태준',
    genre: ['스토리', '드라마'],
    day: 'mon',
  },
  {
    webtoonId: 728750,
    title: '장씨세가 호위무사',
    author: '김인호 / 조형근',
    des: "'당신이 부른 것이오. 나란 사람을...' 은둔고수 광휘. 호위무사 되다. 웹소설 원작 웰메이드 무협 시대극!",
    url: 'https://comic.naver.com/webtoon/list?titleId=728750&weekday=mon',
    img: 'https://image-comic.pstatic.net/webtoon/728750/thumbnail/thumbnail_IMAG21_47c21251-b213-4882-bacc-15adce1acfc8.jpg',
    service: 'naver',
    searchKeyword: '장씨세가호위무사김인호조형근',
    genre: ['스토리', '무협', '사극'],
    day: 'mon',
  },
  {
    webtoonId: 795297,
    title: '신화급 귀속 아이템을 손에 넣었다',
    author: '정선율 / 헤스',
    des: "D급 무투계 레이더로 마법계 레이더들의 고기방패나 하며 별 볼 일 없이 살던 재현. 그러던 어느 날, 던전에서 우연히 '오딘의 눈' 이라는 최강의 귀속 아이템을 얻게 됐다. 신의 눈을 가진 자, 세계를 구할 신의 대적자의 운명을 개척하라!",
    url: 'https://comic.naver.com/webtoon/list?titleId=795297&weekday=mon',
    img: 'https://image-comic.pstatic.net/webtoon/795297/thumbnail/thumbnail_IMAG21_4134925888999731505.jpg',
    service: 'naver',
    searchKeyword: '신화급귀속아이템을손에넣었다정선율헤스',
    genre: ['스토리', '판타지'],
    day: 'mon',
  },
  {
    webtoonId: 602910,
    title: '윈드브레이커',
    author: '조용석',
    des: '혼자서 자전거를 즐겨타던 모범생 조자현. 원치 않게 자전거 크루의 일에 자꾸 휘말리게 되는데... 자유를 꿈꾸는 청춘들의 스트릿라이딩 드라마!',
    url: 'https://comic.naver.com/webtoon/list?titleId=602910&weekday=mon',
    img: 'https://image-comic.pstatic.net/webtoon/602910/thumbnail/thumbnail_IMAG21_e861f2cf-6157-4d33-8e02-7b4cbf0a8baf.jpg',
    service: 'naver',
    searchKeyword: '윈드브레이커조용석',
    genre: ['스토리', '스포츠'],
    day: 'mon',
  },
  {
    webtoonId: 774863,
    title: '팔이피플',
    author: '매미 / 희세',
    des: '<마스크걸>, <위대한 방옥숙> 매미/희세 작가의 신작! SNS에서 육아용품 파는 평범한 유부녀 박주연, 그녀의 고등학교 동창인 김예희는 팔로워 70만의 셀럽으로 엄청난 부와 명성을 누리는 중이다. 박주연은 김예희를 미워하는 동시에 집착하고 있는데, 과연 그녀는 김예희의 과거를 폭로하고 셀럽으로 올라설 수 있을까?',
    url: 'https://comic.naver.com/webtoon/list?titleId=774863&weekday=mon',
    img: 'https://image-comic.pstatic.net/webtoon/774863/thumbnail/thumbnail_IMAG21_3689684179498578529.jpg',
    service: 'naver',
    searchKeyword: '팔이피플매미희세',
    genre: ['스토리', '드라마'],
    day: 'mon',
  },
  {
    webtoonId: 183559,
    title: '신의 탑',
    author: 'SIU',
    des: '자신의 모든 것이었던 소녀를 쫓아 탑에 들어온 소년 그리고 그런 소년을 시험하는 탑',
    url: 'https://comic.naver.com/webtoon/list?titleId=183559&weekday=mon',
    img: 'https://image-comic.pstatic.net/webtoon/183559/thumbnail/thumbnail_IMAG21_5f3fec31-5c95-4afe-a73f-3046288edb47.jpg',
    service: 'naver',
    searchKeyword: '신의탑SIU',
    genre: ['스토리', '판타지'],
    day: 'mon',
  },
  {
    webtoonId: 654774,
    title: '소녀의 세계',
    author: '모랑지',
    des: '완벽해 보이지만 사실 외로웠던 백조들과 맘씨 착한 오리가 만나 여러 갈등을 함께 겪으며 진짜 친구가 되어가는 소녀들의 찐 우정물',
    url: 'https://comic.naver.com/webtoon/list?titleId=654774&weekday=mon',
    img: 'https://image-comic.pstatic.net/webtoon/654774/thumbnail/thumbnail_IMAG21_4048794550434817075.jpg',
    service: 'naver',
    searchKeyword: '소녀의세계모랑지',
    genre: ['스토리', '드라마'],
    day: 'mon',
  },
  {
    webtoonId: 739115,
    title: '앵무살수',
    author: '김성진',
    des: '평범한 뱃사공으로 살고 있는 노소하. 하지만 그의 정체는 전설적인 구파검법의 후계자다. 이제 진시황이 남긴 비서 선근경을 향한 살수행이 시작된다.',
    url: 'https://comic.naver.com/webtoon/list?titleId=739115&weekday=mon',
    img: 'https://image-comic.pstatic.net/webtoon/739115/thumbnail/thumbnail_IMAG21_7077747896626722102.jpg',
    service: 'naver',
    searchKeyword: '앵무살수김성진',
    genre: ['스토리', '판타지'],
    day: 'mon',
  },
  {
    webtoonId: 783053,
    title: '김부장',
    author: '박태준 만화회사 / 정종택',
    des: "“제발 안경 쓴 아저씨는 건들지 말자…” 오직 자신의 딸 '민지'를 위해 특수요원직을 관두고 평범함을 선택한 가장 김부장. 그러던 어느 날 민지가 소리소문 없이 사라지고, 김부장은 자신을 감시하는 국가를 적으로 돌리면서까지 딸을 찾아나서기 시작하는데... [외모지상주의], [싸움독학] 그리고 [인생존망]의 세계관을 잇는 공식 스핀오프 작품!",
    url: 'https://comic.naver.com/webtoon/list?titleId=783053&weekday=tue',
    img: 'https://image-comic.pstatic.net/webtoon/783053/thumbnail/thumbnail_IMAG21_d7732f14-26da-4e35-8762-660cc87b53f1.jpg',
    service: 'naver',
    searchKeyword: '김부장박태준만화회사정종택',
    genre: ['스토리', '액션'],
    day: 'tue',
  },
  {
    webtoonId: 790713,
    title: '대학원 탈출일지',
    author: '요다',
    des: '연구에 꿈을 가지고 대학원을 선택한 병아리 요다. 예상과는 다르게 연구에 관심 없는 교수님과 똥군기의 연구실 분위기에 당황한다. 요다는 과연 무사히 대학원을 탈출할 수 있을 것인가?!',
    url: 'https://comic.naver.com/webtoon/list?titleId=790713&weekday=tue',
    img: 'https://image-comic.pstatic.net/webtoon/790713/thumbnail/thumbnail_IMAG21_3919364435331003700.jpg',
    service: 'naver',
    searchKeyword: '대학원탈출일지요다',
    genre: ['에피소드', '일상'],
    day: 'tue',
  },
  {
    webtoonId: 784248,
    title: '내가 키운 S급들',
    author: 'seri / 비완 / 근서',
    des: "F급 헌터. 그것도 잘나가는 S급 동생 발목이나 잡는 쓸모없고 찌질한 F급 형. 개판된 인생 대충 살다가 결국 동생 목숨까지 잡아먹고 회귀한 내게 주어진 칭호, '완벽한 양육자'. 그래, 이번에는 나대지 말고 얌전히 잘난놈들 뒷바라지나 해 주자. 라고 생각했는데, S급들이 좀 이상하다.",
    url: 'https://comic.naver.com/webtoon/list?titleId=784248&weekday=tue',
    img: 'https://image-comic.pstatic.net/webtoon/784248/thumbnail/thumbnail_IMAG21_20a8aca7-23d3-4bc0-9916-a31ebc884ca8.jpg',
    service: 'naver',
    searchKeyword: '내가키운S급들seri비완근서',
    genre: ['스토리', '판타지'],
    day: 'tue',
  },
  {
    webtoonId: 703846,
    title: '여신강림',
    author: '야옹이',
    des: '네웹 대표 글로벌 인기작! 주경, 수호, 서준. 세 청춘의 두근두근 눈호강 로맨스~♡ 메이크업으로 여신이 된 주경이는 꿈과 사랑을 이룰 수 있을까?',
    url: 'https://comic.naver.com/webtoon/list?titleId=703846&weekday=tue',
    img: 'https://image-comic.pstatic.net/webtoon/703846/thumbnail/thumbnail_IMAG21_3617626786448291892.jpg',
    service: 'naver',
    searchKeyword: '여신강림야옹이',
    genre: ['스토리', '로맨스'],
    day: 'tue',
  },
  {
    webtoonId: 730656,
    title: '사신소년',
    author: '류',
    des: '수명을 대가로 죽은 자의 능력을 빌리는 소년! 화려한 액션에서 부터 스포츠, 두뇌 플레이까지 한계는 없다!',
    url: 'https://comic.naver.com/webtoon/list?titleId=730656&weekday=tue',
    img: 'https://image-comic.pstatic.net/webtoon/730656/thumbnail/thumbnail_IMAG21_fc6d8dbf-eed2-43d0-af45-2edb3cc4244e.jpg',
    service: 'naver',
    searchKeyword: '사신소년류',
    genre: ['스토리', '액션'],
    day: 'tue',
  },
  {
    webtoonId: 796152,
    title: '마루는 강쥐',
    author: '모죠',
    des: '우리 집 강아지 마루가 사람이 되었다, 그것도 5살 아이로! 강아지 + 어린아이의 무한 에너지와 호기심을 지닌 사고뭉치 강쥐 탄생! 마루야~! 또 어디가!!! 유쾌한 이웃들과 우당탕탕 즐거운 마루의 나날들',
    url: 'https://comic.naver.com/webtoon/list?titleId=796152&weekday=tue',
    img: 'https://image-comic.pstatic.net/webtoon/796152/thumbnail/thumbnail_IMAG21_26b9c1d8-ca2d-4fc7-87ea-a3334634236a.jpg',
    service: 'naver',
    searchKeyword: '마루는강쥐모죠',
    genre: ['에피소드', '개그'],
    day: 'tue',
  },
  {
    webtoonId: 743139,
    title: '한림체육관',
    author: '혜성 / 이석재',
    des: "'세상에서 가장 강한 남자가 되고 싶다.' 그릇된 강함을 실천하던 전영하가 한림체육관에 들어와 진정한 강함을 깨닫고 무도인으로 거듭나는 학원 액션물",
    url: 'https://comic.naver.com/webtoon/list?titleId=743139&weekday=tue',
    img: 'https://image-comic.pstatic.net/webtoon/743139/thumbnail/thumbnail_IMAG21_6012f944-ea1f-4328-ba22-bca09be494ee.jpg',
    service: 'naver',
    searchKeyword: '한림체육관혜성이석재',
    genre: ['에피소드', '액션'],
    day: 'tue',
  },
  {
    webtoonId: 789979,
    title: '멸망 이후의 세계',
    author: 'S-Cynan / 언데드 감자 / 싱숑',
    des: '<전지적 독자 시점> 싱숑 작가 원작. 이것은 모두가 과거로 돌아갈 때 마지막까지 회귀하지 않았던 한 사나이의 이야기다.',
    url: 'https://comic.naver.com/webtoon/list?titleId=789979&weekday=tue',
    img: 'https://image-comic.pstatic.net/webtoon/789979/thumbnail/thumbnail_IMAG21_3918466168707821881.jpg',
    service: 'naver',
    searchKeyword: '멸망이후의세계S-Cynan언데드감자싱숑',
    genre: ['스토리', '판타지'],
    day: 'tue',
  },
  {
    webtoonId: 804783,
    title: '사변괴담',
    author: '강태진',
    des: '전쟁 발발 후. 영남의 가족은 남쪽에 있는 숙부의 집으로 피난을 간다. 숙부의 집에는 처음 보는 음산한 분위기의 여자가 자신을 새로운 숙모라고 소개한다. 온몸에 붕대를 감은 채 몸 져 누워있는 숙부도 이상하다. 한밤중 홀로 피의 의식을 치르는 숙모. 정체를 알 수 없는 할머니 귀신. 어디론가 사라진 아버지와 어머니. 혼란과 공포 가운데 놓인 영남과 어린 동생 영순은 이 집을 무사히 빠져나갈 수 있을까?',
    url: 'https://comic.naver.com/webtoon/list?titleId=804783&weekday=tue',
    img: 'https://image-comic.pstatic.net/webtoon/804783/thumbnail/thumbnail_IMAG21_a80f7760-3c93-4002-84d4-eece85593f84.jpg',
    service: 'naver',
    searchKeyword: '사변괴담강태진',
    genre: ['옴니버스', '스릴러'],
    day: 'tue',
  },
  {
    webtoonId: 747269,
    title: '전지적 독자 시점',
    author: 'UMI / 슬리피-C / 싱숑',
    des: "'이건 내가 아는 그 전개다' 한순간에 세계가 멸망하고, 새로운 세상이 펼쳐졌다. 오직 나만이 완주했던 소설 세계에서 평범했던 독자의 새로운 삶이 시작된다.",
    url: 'https://comic.naver.com/webtoon/list?titleId=747269&weekday=wed',
    img: 'https://image-comic.pstatic.net/webtoon/747269/thumbnail/thumbnail_IMAG21_aabd9952-ff45-47a2-a543-33f19a5c6708.jpg',
    service: 'naver',
    searchKeyword: '전지적독자시점UMI슬리피-C싱숑',
    genre: ['스토리', '판타지'],
    day: 'wed',
  },
  {
    webtoonId: 804862,
    title: '백XX',
    author: '박태준 만화회사, 병장 / 펀치킥',
    des: "정보사(HID) 요원 '백이수'와 범죄 조직의 보스인 쌍둥이 형 '백도경'. 같은 얼굴 다른 삶을 살아온 쌍둥이 형제. 조직에 배신당한 동생은 자신의 신분을 버리고 형이 되기로 한다. 정보사요원, 범죄 조직의 보스가 되다...!",
    url: 'https://comic.naver.com/webtoon/list?titleId=804862&weekday=wed',
    img: 'https://image-comic.pstatic.net/webtoon/804862/thumbnail/thumbnail_IMAG21_e2814dcb-83ae-477a-9149-d20fad5bdf92.jpg',
    service: 'naver',
    searchKeyword: '백XX박태준만화회사병장펀치킥',
    genre: ['스토리', '액션'],
    day: 'wed',
  },
  {
    webtoonId: 775141,
    title: '66666년 만에 환생한 흑마법사',
    author: '팀 더 지크 / 파사 / 화봉',
    des: "강대했던 흑마법사 디아블로 볼피르. 12신의 계략에 당해 억겁 속에 봉인되었지만, 그로부터 66666년이 흘러 다시금 이 땅에 강림한다! '응애!' 웰턴 백작의 갓 태어난 장남으로. 딥다크 매직 판타지 시작!",
    url: 'https://comic.naver.com/webtoon/list?titleId=775141&weekday=wed',
    img: 'https://image-comic.pstatic.net/webtoon/775141/thumbnail/thumbnail_IMAG21_11d97e88-9ccf-4e7a-a10d-dde42725e3fa.jpg',
    service: 'naver',
    searchKeyword: '66666년만에환생한흑마법사팀더지크파사화봉',
    genre: ['스토리', '판타지'],
    day: 'wed',
  },
  {
    webtoonId: 717481,
    title: '일렉시드',
    author: '손제호 / 제나',
    des: '<노블레스> 손제호 작가와 <소녀더와일즈> 제나 작가가 만났다! 고양이 몸에 깃든 각성자 카이든과 각성능력을 숨겨온 고등학생 지우 러블리 2인조의 액션 판타지',
    url: 'https://comic.naver.com/webtoon/list?titleId=717481&weekday=wed',
    img: 'https://image-comic.pstatic.net/webtoon/717481/thumbnail/thumbnail_IMAG21_3545800975505057126.jpg',
    service: 'naver',
    searchKeyword: '일렉시드손제호제나',
    genre: ['스토리', '액션'],
    day: 'wed',
  },
  {
    webtoonId: 784417,
    title: '무림서부',
    author: '웨스트 / 정한길 / 컵라면',
    des: '황제가 무공을 통한 철혈정치로 제국을 천년동안 유지함에 따라, 오로지 황군 무공만이 힘이요 법도로 살아남고, 고전 무공들은 스러지고 만다. 이런 세계에 환생한 무협지 마니아, 주인공 장건. 과연 그는 동경하던 고전 무공을 되살릴 수 있을까. 서부 대륙 개척지에서 벌어지는 정통 무협의 정수!',
    url: 'https://comic.naver.com/webtoon/list?titleId=784417&weekday=wed',
    img: 'https://image-comic.pstatic.net/webtoon/784417/thumbnail/thumbnail_IMAG21_f997ffe9-465a-4be8-a0bb-b5d0ef5cedea.jpg',
    service: 'naver',
    searchKeyword: '무림서부웨스트정한길컵라면',
    genre: ['스토리', '무협', '사극'],
    day: 'wed',
  },
  {
    webtoonId: 701535,
    title: '격기3반',
    author: '이학',
    des: '한국이 세계 격투기의 중심이 된 세상. 전국 탑 클래스 격투기 학생들만 모인 남일고에 약골 소년 주지태가 돌연 투입된다. 신체적 약점이 상쇄되는 무술 ‘주짓수’를 통해, 주지태는 격기반의 정점에 오를 수 있을 것인가…?',
    url: 'https://comic.naver.com/webtoon/list?titleId=701535&weekday=wed',
    img: 'https://image-comic.pstatic.net/webtoon/701535/thumbnail/thumbnail_IMAG21_2abe5b1a-9104-417f-9995-0db15c6db7be.jpg',
    service: 'naver',
    searchKeyword: '격기3반이학',
    genre: ['스토리', '스포츠'],
    day: 'wed',
  },
  {
    webtoonId: 738694,
    title: '튜토리얼 탑의 고인물',
    author: '토프 / 방구석김씨',
    des: '전 세계에 몬스터와 함께 등장한 의문의 탑들. 이 탑들은 사람들을 선별하고, 선별 저들은 100층까지 클리어를 해야 다시 세상으로 나갈 수 있다. 이에 주인공 김현우는 다른 선별된 사람들과 함께 100층까지 공략하지만 알 수 없는 이유로 나가지 못하고 다시 1층으로 돌아와버린다. 그 후 김현우는 탑을 나가기 위해 수없이 100층을 반복하여 깨고… 그런 생활을 12년 동안이나 반복하던 어느 날, 갑자기 루프가 풀려 세상 밖으로 나갈 수 있게 된다.',
    url: 'https://comic.naver.com/webtoon/list?titleId=738694&weekday=wed',
    img: 'https://image-comic.pstatic.net/webtoon/738694/thumbnail/thumbnail_IMAG21_7366031057188643120.jpg',
    service: 'naver',
    searchKeyword: '튜토리얼탑의고인물토프방구석김씨',
    genre: ['스토리', '액션'],
    day: 'wed',
  },
  {
    webtoonId: 750184,
    title: '나쁜사람',
    author: '둠스',
    des: '착한 남자가 좋다는 그녀의 이상형이 되기 위해 10년 동안 노력했다. 그런데! 갑자기 나쁜 남자가 좋다는 그녀... 오늘부터 난... 나쁜 남자로 다시 태어난다.',
    url: 'https://comic.naver.com/webtoon/list?titleId=750184&weekday=wed',
    img: 'https://image-comic.pstatic.net/webtoon/750184/thumbnail/thumbnail_IMAG21_4049077335359959091.jpg',
    service: 'naver',
    searchKeyword: '나쁜사람둠스',
    genre: ['에피소드', '액션'],
    day: 'wed',
  },
  {
    webtoonId: 800770,
    title: '재벌집 막내아들',
    author: 'JP / 김병관 / 산경',
    des: '[화제의 드라마 원작 웹툰!] 13년 동안의 수고를 배신으로 돌려받다니! 머슴처럼 살다 버려진 순양그룹의 실장, 윤현우. 모든 게 끝났다 싶었을 즘, 순양그룹 진 회장의 손주 진도준으로 깨어난다! 하지만 상속권과는 거리가 먼 재벌집 막내아들 진도준. 과연 그는 가족 정치극에서 최후의 승자가 될 수 있을 것인가! 순양그룹을 집어삼키기 위한 윤현우의 통쾌한 복수극이 시작된다!',
    url: 'https://comic.naver.com/webtoon/list?titleId=800770&weekday=thu',
    img: 'https://image-comic.pstatic.net/webtoon/800770/thumbnail/thumbnail_IMAG21_d2e1e7ee-fc83-4030-a1e7-200378bc088f.jpg',
    service: 'naver',
    searchKeyword: '재벌집막내아들JP김병관산경',
    genre: ['스토리', '드라마'],
    day: 'thu',
  },
  {
    webtoonId: 570503,
    title: '연애혁명',
    author: '232',
    des: '평범하면서 금사빠인 고등학생 순정남 공주영은 까칠하고 차가운 여학생 왕자림을 보고 사랑에 빠져버린다.너무 다른 둘, 괜찮을까?',
    url: 'https://comic.naver.com/webtoon/list?titleId=570503',
    img: 'https://image-comic.pstatic.net/webtoon/570503/thumbnail/thumbnail_IMAG21_85e39ba0-3fc6-4ddb-9e78-5e8879b7d3d9.jpg',
    service: 'naver',
    searchKeyword: '연애혁명232',
    genre: ['스토리', '드라마'],
    day: 'thu',
  },
  {
    webtoonId: 747271,
    title: '나노마신',
    author: '현절무 / 금강불괴 / 한중월야',
    des: '갖은 멸시와 목숨의 위협을 받던 마교의 사생아 천여운, 미래에서 나타난 후손이 천여운의 몸에 나노 머신을 주입한 후 그의 인생이 송두리째 바뀐다.마교를 넘어 무림 최고의 자리에 오르기 위한 천여운의 거침없는 이야기가 시작된다!',
    url: 'https://comic.naver.com/webtoon/list?titleId=747271',
    img: 'https://image-comic.pstatic.net/webtoon/747271/thumbnail/thumbnail_IMAG21_701ae78e-794c-417f-b5a8-3adf6f9456aa.jpg',
    service: 'naver',
    searchKeyword: '나노마신현절무금강불괴한중월야',
    genre: ['스토리', '무협', '사극'],
    day: 'thu',
  },
  {
    webtoonId: 776255,
    title: '천마육성',
    author: '광휘 / 조형근',
    des: '마교의 태왕각주 ‘사마귀’의 명령으로 화산파 출목지역으로 파견나간 비객조.‘설휘’는 화산파의 절대고수 ‘구종명’에게 죽임을 당할 위기에 처한다.그 때 눈앞에 상태창이 나타나고 정찰임무를 받기 직전으로 회귀하게 된다.설휘는 자신이 전생에서 죽임을 당했던 똑같은 임무를 받게 되자 주변의 환경을 조금이라도 바꾸어 살아남고자 발버둥친다.고비마다 눈앞에 나타나는 선택창, 미래를 알 수 없는 지문들. 삶과 죽음이 공존하는 세상 안에서 최선의 방법을 찾아 나선다.',
    url: 'https://comic.naver.com/webtoon/list?titleId=776255',
    img: 'https://image-comic.pstatic.net/webtoon/776255/thumbnail/thumbnail_IMAG21_4121980471072928565.jpg',
    service: 'naver',
    searchKeyword: '천마육성광휘조형근',
    genre: ['무협'],
    day: 'thu',
  },
  {
    webtoonId: 783888,
    title: '현실퀘스트',
    author: '이주운 / 태성',
    des: '게임 아이템을 가져오라는 일진의 협박으로 인해일주일간 밤샘 게임을 하다 죽음을 맞이한 비운의 게임셔틀 하도완그 순간 일주일 전 교실에서 리스폰되는데...모든 것이 그날과 똑같다. 달라진 것은 단 하나, 눈앞에 떠있는 <퀘스트 알림>!뭐? 내가 지금껏 하던 게임들의 스킬을 이용해서 일진을 때려잡으라고?!?!',
    url: 'https://comic.naver.com/webtoon/list?titleId=783888',
    img: 'https://image-comic.pstatic.net/webtoon/783888/thumbnail/thumbnail_IMAG21_56cdafe8-11a4-40b7-90a7-2e72b0b20642.jpg',
    service: 'naver',
    searchKeyword: '현실퀘스트이주운태성',
    genre: ['스토리', '액션'],
    day: 'thu',
  },
  {
    webtoonId: 780170,
    title: '나 혼자 네크로맨서',
    author: '김경열 / 김동준 / 지점장',
    des: '곧 세상이 멸망한다.전설 속에나 나올 법한 몬스터들이 각지에 출현한다.그리고 사람들을 잡아먹고, 길거리를 점령하며, 빌딩과 지하철에 던전을 만들기 시작한다.멸망한 세계에서 살아남기 위해 단 한 가지 직업을 고를 수 있다.당신은 무슨 직업을 고르겠는가?"네크로맨서"나에게는 멸망이 무대이고, 죽음이 자산이 된다.',
    url: 'https://comic.naver.com/webtoon/list?titleId=780170',
    img: 'https://image-comic.pstatic.net/webtoon/780170/thumbnail/thumbnail_IMAG21_c8b82359-da45-480c-95fd-aa9ae794d6be.jpg',
    service: 'naver',
    searchKeyword: '나혼자네크로맨서김경열김동준지점장',
    genre: ['스토리', '판타지'],
    day: 'thu',
  },
  {
    webtoonId: 746857,
    title: '무사만리행',
    author: '운 / 배민기',
    des: '2세기 후반, 마한연맹 고리국(古離國)의 무사 나루.믿었던 스승의 배신으로 나라가 멸망하고, 평생을 바쳐 지켜주겠노라 맹세했던 소단공주의 행방이 묘연해진다. 유일한 단서인 서역으로 떠났다는 배신자의 말에 나루는 로마제국의 검투 노예로 팔려가 공주의 행방을 찾고 자유를 얻기 위해 처절한 사투를 벌인다.',
    url: 'https://comic.naver.com/webtoon/list?titleId=746857',
    img: 'https://image-comic.pstatic.net/webtoon/746857/thumbnail/thumbnail_IMAG21_fb7d7fcd-19f1-49eb-9cc8-aae9622cdd04.jpg',
    service: 'naver',
    searchKeyword: '무사만리행운배민기',
    genre: ['스토리', '무협', '사극'],
    day: 'thu',
  },
  {
    webtoonId: 796827,
    title: '회귀한 천재 헌터의 슬기로운 청소생활',
    author: '고일고일 / 달비트',
    des: '세계 최초 SSS랭크 천재 헌터 김준우. 어느 날 습격을 당해 죽게 되고, 10년 전으로 회귀한다.​스킬은 모두 봉인됐고, 해제를 위해서는 극한 직업인 던전 청소부로 일을 해야 하는데?!​하지만 이 청소부, 남다르다! 현직 헌터보다 더 강한 전직 헌터의 망나니식 청소가 시작된다!원작 제공 : 영상출판미디어',
    url: 'https://comic.naver.com/webtoon/list?titleId=796827',
    img: 'https://image-comic.pstatic.net/webtoon/796827/thumbnail/thumbnail_IMAG21_3990814210026202423.jpg',
    service: 'naver',
    searchKeyword: '회귀한천재헌터의슬기로운청소생활고일고일달비트',
    genre: ['스토리', '판타지'],
    day: 'thu',
  },
  {
    webtoonId: 795643,
    title: '호랑신랑뎐',
    author: '고추참치',
    des: '산 속에 사는 금슬 좋은 부부! 그러나 이 부부에겐 어딘가 특별한 점이 있다. 그건 바로.. 신랑이 사람처럼 걸어다니고 말도 할 수 있는 호랑이라는데..? 무뚝뚝하지만 마음씨 착한 호랑이 신랑과 장난스럽고 수다스러운 인간 아내가 만나 벌어지는 좌충우돌 일상 이야기!',
    url: 'https://comic.naver.com/webtoon/list?titleId=795643',
    img: 'https://image-comic.pstatic.net/webtoon/795643/thumbnail/thumbnail_IMAG21_bf51fa0f-e374-49f8-973d-c17c5385bbef.jpg',
    service: 'naver',
    searchKeyword: '호랑신랑뎐고추참치',
    genre: ['스토리', '판타지'],
    day: 'thu',
  },
  {
    webtoonId: 641253,
    title: '외모지상주의',
    author: '박태준',
    des: '못생기고 뚱뚱하다고 괴롭힘을 당하며  루저 인생만 살아온 내가 잘생겨졌다는 이유로 인싸가 됐다.어느 날 자고 일어났더니 갑자기 완벽한 외모와 몸을 지닌 사람이 되어 깨어난다면?',
    url: 'https://comic.naver.com/webtoon/list?titleId=641253',
    img: 'https://image-comic.pstatic.net/webtoon/641253/thumbnail/thumbnail_IMAG21_01672165-03c8-44b1-ba0e-ef82c9cfcd10.jpg',
    service: 'naver',
    searchKeyword: '외모지상주의박태준',
    genre: ['스토리', '드라마'],
    day: 'fri',
  },
  {
    webtoonId: 773797,
    title: '나 혼자 만렙 뉴비',
    author: 'WAN.Z / 스윙뱃 / 메슬로우',
    des: '게임 너튜버로 활동 중인 주인공 진혁은 유일하게 [시련의 탑]의 엔딩을 봤지만, 게임의 인기가 하락하며 더 이상 게임 너튜버로서의 삶도 유지하기 힘들어진다.엔딩을 보았기에 이대로 게임을 마무리하려는 진혁. 바로 그날, [시련의 탑]은 현실이 되었다.게임의 모든 요소를 다 알고 있는 진혁은 누구보다 빠르게 모든 것을 차지한다!"진짜 고인물이 뭔지 보여주지."',
    url: 'https://comic.naver.com/webtoon/list?titleId=773797',
    img: 'https://image-comic.pstatic.net/webtoon/773797/thumbnail/thumbnail_IMAG21_74f87a34-cf6d-4838-8a80-768bdb2f78a9.jpg',
    service: 'naver',
    searchKeyword: '나혼자만렙뉴비WAN.Z스윙뱃메슬로우',
    genre: ['스토리', '판타지'],
    day: 'fri',
  },
  {
    webtoonId: 790245,
    title: '어쩌다보니 천생연분',
    author: '꿀타래 / 담초',
    des: '집에 얹혀산 지 몇 년 차더라..? 올해 32살을 맞이한 한지아(일하지 않는 프리랜서/무직)는 주변의 결혼하라는 눈칫밥에 오늘도 고통받는데.. 때마침 명절을 맞이하여 고향에 내려온 소꿉친구 민철 또한 같은 고민이 있었으니.그러면 쉬운 해결 방법이 있잖아?!? 그렇게 홧김에 결혼한 두 사람.그런데 막상 결혼해 보니... 어라?? 생각보다 너무 잘 맞는다?!',
    url: 'https://comic.naver.com/webtoon/list?titleId=790245',
    img: 'https://image-comic.pstatic.net/webtoon/790245/thumbnail/thumbnail_IMAG21_3545003845982959922.jpg',
    service: 'naver',
    searchKeyword: '어쩌다보니천생연분꿀타래담초',
    genre: ['스토리', '로맨스'],
    day: 'fri',
  },
  {
    webtoonId: 777767,
    title: '역대급 영지 설계사',
    author: '이현민 / 김현수 / 문백경',
    des: '소설 속 귀족이 된 토목공학도 김수호. 그런데 뭐? 내 영지가 곧 망할 거라고? 그럼 살려야지. 설계하고, 건설하고, 분양해서. [전 대륙이 기다려온 특별한 기회! 퍼펙트한 교통, 최상의 학군, 쾌적한 숲세권, 원스톱 프리미엄 영지 라이프의 프론테라 남작령이 여러분을 기다립니다. 선착순 분양계약중!]',
    url: 'https://comic.naver.com/webtoon/list?titleId=777767',
    img: 'https://image-comic.pstatic.net/webtoon/777767/thumbnail/thumbnail_IMAG21_cc85f891-272b-450a-b642-cffe1568ab71.jpg',
    service: 'naver',
    searchKeyword: '역대급영지설계사이현민김현수문백경',
    genre: ['스토리', '판타지'],
    day: 'fri',
  },
  {
    webtoonId: 753478,
    title: '데드퀸',
    author: '김규삼',
    des: '절망에 빠져 죽음이 임박했을때, 진짜 여왕이 재림한다!하이브 세계관의 장대한 끝, 데드퀸',
    url: 'https://comic.naver.com/webtoon/list?titleId=753478',
    img: 'https://image-comic.pstatic.net/webtoon/753478/thumbnail/thumbnail_IMAG21_4049077133597095219.jpg',
    service: 'naver',
    searchKeyword: '데드퀸김규삼',
    genre: ['스토리', '판타지'],
    day: 'fri',
  },
  {
    webtoonId: 725586,
    title: '1초',
    author: '시니 / 광운',
    des: '구조율 100%의 전설적인 소방관.  그의 특별한 능력은 긴장하는 순간, 미래가 보인다는 것! 촌각을 다투는 진짜 소방관들의 이야기',
    url: 'https://comic.naver.com/webtoon/list?titleId=725586',
    img: 'https://image-comic.pstatic.net/webtoon/725586/thumbnail/thumbnail_IMAG21_17f81846-d1a9-43fd-83a4-f9e966b6b977.jpg',
    service: 'naver',
    searchKeyword: '1초시니광운',
    genre: ['스토리', '드라마'],
    day: 'fri',
  },
  {
    webtoonId: 712362,
    title: '개를 낳았다',
    author: '이선',
    des: '사랑스러운 너와의 첫 만남부터 이별까지. 처음으로 반려견을 키우게 된 다나와 모든것이 처음인 강아지 명동이가 만나 함께 살아가는 이야기. 강아지 수명 20년. 너와 내가 함께하는 20년 동안 우린 어떤 일을 겪게 될까?',
    url: 'https://comic.naver.com/webtoon/list?titleId=712362',
    img: 'https://image-comic.pstatic.net/webtoon/712362/thumbnail/thumbnail_IMAG21_7220173143199539507.jpg',
    service: 'naver',
    searchKeyword: '개를낳았다이선',
    genre: ['스토리', '드라마'],
    day: 'fri',
  },
  {
    webtoonId: 711422,
    title: '삼국지톡',
    author: '무적핑크 / 이리',
    des: '"유비, 조조, 손권 등 영웅들이 활약하던 후한, 그 난세에 핸드폰이 있었다면?메신저로 소통하고, 개인 방송으로 군사를 모집한다! 이제껏 보지 못한 완전히 새로운 삼국지!"',
    url: 'https://comic.naver.com/webtoon/list?titleId=711422',
    img: 'https://image-comic.pstatic.net/webtoon/711422/thumbnail/thumbnail_IMAG21_fd8cb5db-01ab-4c7b-a2a9-920d4479d5f7.jpg',
    service: 'naver',
    searchKeyword: '삼국지톡무적핑크이리',
    genre: ['에피소드', '무협', '사극'],
    day: 'fri',
  },
  {
    webtoonId: 751168,
    title: '상남자',
    author: '하늘소 / 도가도 / 김태궁',
    des: '오로지 성공만을 바라보며 기업 정점의 자리까지 오른, 최고의 샐러리맨 한유현.대가로 사랑하던 모든 이를 잃어버린 후, 후회 섞인 인생을 돌아보는데...어느 날 모든 기억을 안은 채, 젊은 시절의 그때로 돌아가게 된다.모든 것의 시작점인 신입사원의 위치에서, 그가 다시 삶을 설계한다!',
    url: 'https://comic.naver.com/webtoon/list?titleId=751168',
    img: 'https://image-comic.pstatic.net/webtoon/751168/thumbnail/thumbnail_IMAG21_529c6125-cf14-435f-94ed-db1a2d499d84.jpg',
    service: 'naver',
    searchKeyword: '상남자하늘소도가도김태궁',
    genre: ['스토리', '드라마'],
    day: 'fri',
  },
  {
    webtoonId: 792651,
    title: '99강화나무몽둥이',
    author: '홍실 / 지페리',
    des: '약육강식이 진리인 가상 현실 게임 "크로노 라이프. 허접이라며 무시만 당하던 "나"는 우연히 얻은 초보용 기본 무기 "나무 뭉둥이" 를 +99 강화까지 성공하게 되고, 본인을 무시하던 놈들을 찾아다니며 몽둥이로 무자비하게 패기 시작하는데..!막장 스케일 사이다 액션 스타트!!',
    url: 'https://comic.naver.com/webtoon/list?titleId=792651',
    img: 'https://image-comic.pstatic.net/webtoon/792651/thumbnail/thumbnail_IMAG21_218f18ef-7f68-4d6a-972c-686a3e9f6138.jpg',
    service: 'naver',
    searchKeyword: '99강화나무몽둥이홍실지페리',
    genre: ['스토리', '판타지'],
    day: 'sat',
  },
  {
    webtoonId: 650305,
    title: '호랑이형님',
    author: '이상규',
    des: '신비한 힘을 가진 아이를 이용하여 세상을 지배하려는 반인반수 흰눈썹! 그리고 얼떨결에 아이의 보호자가 된 괴물호랑이 빠르와 착호갑사 지망생 가우리!이제 힘을 합쳐 흰눈썹으로부터 아이와 세상을 지켜라!!!',
    url: 'https://comic.naver.com/webtoon/list?titleId=650305',
    img: 'https://image-comic.pstatic.net/webtoon/650305/thumbnail/thumbnail_IMAG21_3631086797392995425.jpg',
    service: 'naver',
    searchKeyword: '호랑이형님이상규',
    genre: ['스토리', '판타지'],
    day: 'sat',
  },
  {
    webtoonId: 727188,
    title: '취사병 전설이 되다',
    author: '제이로빈 / 이진수',
    des: '대한민국 대표 흙수저, 강성재. 불안하기만 한 군생활에 한줄기 빛처럼 다가온 전설의 취사병이 될 기회!',
    url: 'https://comic.naver.com/webtoon/list?titleId=727188',
    img: 'https://image-comic.pstatic.net/webtoon/727188/thumbnail/thumbnail_IMAG21_d4726354-42bc-4bdf-b500-02c951082eeb.jpg',
    service: 'naver',
    searchKeyword: '취사병전설이되다제이로빈이진수',
    genre: ['스토리', '판타지'],
    day: 'sat',
  },
  {
    webtoonId: 597447,
    title: '프리드로우',
    author: '전선욱',
    des: '한태성을 중심으로 벌어지는 다양한 청춘들의 스펙타클한 학원 시트콤 드라마',
    url: 'https://comic.naver.com/webtoon/list?titleId=597447',
    img: 'https://image-comic.pstatic.net/webtoon/597447/thumbnail/thumbnail_IMAG21_37e97fb1-5572-45cc-8672-2a60b6cb768e.jpg',
    service: 'naver',
    searchKeyword: '프리드로우전선욱',
    genre: ['스토리', '드라마'],
    day: 'sat',
  },
  {
    webtoonId: 801589,
    title: '놓지마 정신줄 시즌3',
    author: '신태훈 / 나승훈',
    des: '놓지마 정신줄이 돌아왔다! 정신줄 세계 10년 후의 이야기.정신줄 세상에 10년이란 세월이 흐른 어느 날, 정신줄 세계에 엄청난 대격변이 일어나게 되는데...인간과 정령이 공존하는 한층 더 정신줄 놓은 세상이 열리고 말았다!',
    url: 'https://comic.naver.com/webtoon/list?titleId=801589',
    img: 'https://image-comic.pstatic.net/webtoon/801589/thumbnail/thumbnail_IMAG21_1b439234-e17d-4fb8-9eef-5d2d4173234c.jpg',
    service: 'naver',
    searchKeyword: '놓지마정신줄시즌3신태훈나승훈',
    genre: ['에피소드', '개그'],
    day: 'sat',
  },
  {
    webtoonId: 787500,
    title: '은탄',
    author: '김규삼',
    des: '흡혈귀와 요괴, 무당이 창궐한 혼란의 조선, 자신을 암흑어사라 칭하는 박문수가 타락한 관아를 파괴하고 다닌다. 다급해진 조정에서는 흡혈귀 왕의 부활을 노리는 암흑어사 박문수를 토벌하라 명하기 위해 갓 무과에 급제한 무관 안손에게 도술과 무술에 능한 도적 홍킬동을 찾아오라 태백산으로 파견한다. <하이브>의 김규삼 작가가 선사하는 요괴 퇴마 개그 판타지 시대극!',
    url: 'https://comic.naver.com/webtoon/list?titleId=787500',
    img: 'https://image-comic.pstatic.net/webtoon/787500/thumbnail/thumbnail_IMAG21_7090184484697487202.jpg',
    service: 'naver',
    searchKeyword: '은탄김규삼',
    genre: ['스토리', '판타지'],
    day: 'sat',
  },
  {
    webtoonId: 721948,
    title: '스터디그룹',
    author: '신형욱 / 유승연',
    des: '우등생을 꿈꾸는 최강 소년의 고교액션활극.공부를 잘 하고 싶지만 애석하게도 싸움 실력에만 재능이 몰빵된 고등학생 윤가민.똥통학교 유성공고에서 스터디그룹을 만드는데….그와 스터디 멤버들의 (진짜로) 피튀기는 입시이야기!',
    url: 'https://comic.naver.com/webtoon/list?titleId=721948',
    img: 'https://image-comic.pstatic.net/webtoon/721948/thumbnail/thumbnail_IMAG21_b5efacb7-c212-422f-bc4a-15cf5dc84408.jpg',
    service: 'naver',
    searchKeyword: '스터디그룹신형욱유승연',
    genre: ['스토리', '액션'],
    day: 'sat',
  },
  {
    webtoonId: 793283,
    title: '악몽의 형상',
    author: '김용키',
    des: '"타인은지옥이다", "관계의종말" 이후 9년..종우와 다은은 여전히 끔찍한 지옥 속에서 살고 있다.그러던 어느 날, 과거 고시원 사건과 펜션 사건을 방불케하는 살인 사건이 벌어지고당시 두 사건을 수사했던 정형사는 종우와 다은을 찾는다.그리고 끔찍했던 악몽은 점점 다가오는 형상이 된다.',
    url: 'https://comic.naver.com/webtoon/list?titleId=793283',
    img: 'https://image-comic.pstatic.net/webtoon/793283/thumbnail/thumbnail_IMAG21_4136055320174945841.jpg',
    service: 'naver',
    searchKeyword: '악몽의형상김용키',
    genre: ['스토리', '스릴러'],
    day: 'sat',
  },
  {
    webtoonId: 805356,
    title: '이종 격투기',
    author: '꼬마비',
    des: '1인 심부름센터를 운영하는 주인공 형담은 보름달이 뜨는 밤이면 다른 인종으로 변해버리는 비밀을 가지고 있다. 통제와 제어가 불가능한 변화는 때에 따라서 백인이나 흑인, 그 외의 다른 인종으로 거듭나는데 형담은 그런 주기마다 자신을 대하는 사람들의 모습과 스스로가 세상을 바라보는 시선의 변화로 인해 고군분투한다.힘든 나날을 보내던 형담은 우연한 사건을 계기로 자신의 비밀이 만천하에 밝혀지게 되고 온갖 매체를 통해 소비되어 가는데...',
    url: 'https://comic.naver.com/webtoon/list?titleId=805356',
    img: 'https://image-comic.pstatic.net/webtoon/805356/thumbnail/thumbnail_IMAG21_d7631c1e-dab2-44b5-97af-c61d5fade064.jpg',
    service: 'naver',
    searchKeyword: '이종격투기꼬마비',
    genre: ['스토리', '드라마'],
    day: 'sat',
  },
  {
    webtoonId: 736277,
    title: '싸움독학',
    author: '박태준 만화회사 / 김정현 스튜디오',
    des: '힘없고 가진거 하나 없이 맞고만 살던 나였는데...우연히 비밀의 뉴튜브를 발견하게 되고 갑자기 떼돈을 벌었다.',
    url: 'https://comic.naver.com/webtoon/list?titleId=736277',
    img: 'https://image-comic.pstatic.net/webtoon/736277/thumbnail/thumbnail_IMAG21_bbbe3f76-021e-4dbc-830a-4358c1abec0c.jpg',
    service: 'naver',
    searchKeyword: '싸움독학박태준만화회사김정현스튜디오',
    genre: ['스토리', '액션'],
    day: 'sun',
  },
  {
    webtoonId: 710751,
    title: '약한영웅',
    author: '서패스 / 김진석',
    des: '“비겁하다…? 애초에 동등한 시작이 아닌데... 체급도 쪽수도 안 맞잖아- 이 X끼들아!!”선천적으로 약한 소년이 상대보다 몇 수 앞을 예측하는 심리전과지형지물을 이용하고, 도구로 살벌하게 끝장내는 파이터로 성장한다.이제 그의 또 다른 이름은 "은장백사"다.',
    url: 'https://comic.naver.com/webtoon/list?titleId=710751',
    img: 'https://image-comic.pstatic.net/webtoon/710751/thumbnail/thumbnail_IMAG21_53aefc06-6bdf-40fb-93ac-fab7242146c6.jpg',
    service: 'naver',
    searchKeyword: '약한영웅서패스김진석',
    genre: ['에피소드', '액션'],
    day: 'sun',
  },
  {
    webtoonId: 758150,
    title: '입학용병',
    author: 'YC / 락현',
    des: '어린 시절 비행기 추락 사고의 유일한 생존자 유이진. 살아남기 위해 용병으로 살아가던 유이진은 10년 후, 가족이 있는 고향으로 돌아왔다.',
    url: 'https://comic.naver.com/webtoon/list?titleId=758150',
    img: 'https://image-comic.pstatic.net/webtoon/758150/thumbnail/thumbnail_IMAG21_4135492154714961716.jpg',
    service: 'naver',
    searchKeyword: '입학용병YC락현',
    genre: ['스토리', '액션'],
    day: 'sun',
  },
  {
    webtoonId: 795262,
    title: '사형소년',
    author: '박태준만화회사, 김숭늉 / 광산',
    des: '대한민국을 뒤흔든 희대의 연쇄살인마 김신! 김신에게 가족을 잃은 지후는 또 다른 피해자 두석을 만나 인간병기로 훈련된다.그리고 살인마를 맨주먹으로 때려죽이기 위해 스스로 교도소로 향하는데..."우리나라는 97년 이후로 사형집행이 되지 않았어. 누군가는 집행해야 하지 않을까?"',
    url: 'https://comic.naver.com/webtoon/list?titleId=795262',
    img: 'https://image-comic.pstatic.net/webtoon/795262/thumbnail/thumbnail_IMAG21_b6090fe4-9f39-4ef9-802e-091184f38e30.jpg',
    service: 'naver',
    searchKeyword: '사형소년박태준만화회사김숭늉광산',
    genre: ['스토리', '스릴러'],
    day: 'sun',
  },
  {
    webtoonId: 779632,
    title: '일타강사 백사부',
    author: '팀 더 지크 / 오리보리 / 간짜장',
    des: '혈교 최고의 무공 교관, 시골 무관의 사부로 환생하다. 그리고 정파 무림의 일타강사로!이름하여 백 사부.그가 이제 전 무림을 참교육한다!',
    url: 'https://comic.naver.com/webtoon/list?titleId=779632',
    img: 'https://image-comic.pstatic.net/webtoon/779632/thumbnail/thumbnail_IMAG21_4048795649913205816.jpg',
    service: 'naver',
    searchKeyword: '일타강사백사부팀더지크오리보리간짜장',
    genre: ['스토리', '무협', '사극'],
    day: 'sun',
  },
  {
    webtoonId: 703844,
    title: '가비지타임',
    author: '2사장',
    des: '한국 최초 한국형 고교스포츠 웹툰!열혈따윈 개나 줘, 낙오자들 뿐인 농구부의 운명은?',
    url: 'https://comic.naver.com/webtoon/list?titleId=703844',
    img: 'https://image-comic.pstatic.net/webtoon/703844/thumbnail/thumbnail_IMAG21_4122261748397257571.jpg',
    service: 'naver',
    searchKeyword: '가비지타임2사장',
    genre: ['스토리', '스포츠'],
    day: 'sun',
  },
  {
    webtoonId: 805156,
    title: '고양이 타타',
    author: '로로',
    des: '할머니 댁에 내려와 여름방학을 보내게 된 중학생 수연은 우연히  꽃봉오리에서 피어난 고양이 타타를 만난다. 수연은 특별한 고양이 타타와 함께 잊을 수 없는 마법 같은 일들을 경험하게 되는데...',
    url: 'https://comic.naver.com/webtoon/list?titleId=805156',
    img: 'https://image-comic.pstatic.net/webtoon/805156/thumbnail/thumbnail_IMAG21_6f3edc71-606d-4454-af42-e2f558137132.jpg',
    service: 'naver',
    searchKeyword: '고양이타타로로',
    genre: ['스토리', '드라마'],
    day: 'sun',
  },
  {
    webtoonId: 785251,
    title: '시월드가 내게 집착한다',
    author: '승우 / 한윤설',
    des: '사랑했던 가족들이 나를 죽였다.과거로 돌아온 나는 내 목숨과 유산을 지키기로 결심하고 라피레온 대공을 찾아갔다.그런데 이 대공가, 심상치 않다.무사히 복수를 마치고, 이혼할 수 있을까?',
    url: 'https://comic.naver.com/webtoon/list?titleId=785251',
    img: 'https://image-comic.pstatic.net/webtoon/785251/thumbnail/thumbnail_IMAG21_3919877924477546549.jpg',
    service: 'naver',
    searchKeyword: '시월드가내게집착한다승우한윤설',
    genre: ['스토리', '로맨스'],
    day: 'sun',
  },
  {
    webtoonId: 803909,
    title: '나 혼자 특성빨로 무한 성장',
    author: '샤이아탄 / 2사랑 / 선운(鮮雲)',
    des: '평생 헌터가 되지 못할 줄 알았다.기회 같은 것은 찾아오지 않을 거라 여겼다.하지만 아니었다.「‘시련의 탑’이 지구 차원의 모든 적합자를 선별해냈습니다.」「난이도를 선택해주십시오.」「선택하는 난이도에 따라서 보상도 커집니다.」이제 내게도 기회가 주어졌다.그것도 아주 특별한.',
    url: 'https://comic.naver.com/webtoon/list?titleId=803909',
    img: 'https://image-comic.pstatic.net/webtoon/803909/thumbnail/thumbnail_IMAG21_764d377c-fe45-40f9-8775-0f6ff92ad421.jpg',
    service: 'naver',
    searchKeyword: '나혼자특성빨로무한성장샤이아탄2사랑선운(鮮雲)',
    genre: ['스토리', '액션'],
    day: 'sun',
  },
  {
    webtoonId: 2745,
    title: '세이렌: 악당과 계약가족이 되었다',
    author: '생얌, 포야, 설이수',
    des: '아리아는 계약 결혼을 제안했다. 그것도, 악마에게 영혼을 팔았다는 발렌타인의 대공자에게. 자신을 지키고, 그를 지키기 위해서. [나와 결혼해.] 아리아는 단풍잎 같은 손으로, 쪽지와 함께 혼인 서약서를 내밀었다. [계약 결혼이니까 10년 뒤에 이혼…….] 그러자 어린 대공자는 쓰고 있던 쪽지를 빼앗아 쫙쫙 찢으며 말했다. “그래서, 도장은 어디에 찍으면 되지?” “크면 이혼해주겠다고 했잖아.” 어느새 훌쩍 자란 악마 대공이, 그녀의 머리카락 위에 경건하게 입을 맞추며 말했다. “어른이 되었으니 어른의 계약을 해야지.',
    url: 'https://webtoon.kakao.com/content/%EC%84%B8%EC%9D%B4%EB%A0%8C-%EC%95%85%EB%8B%B9%EA%B3%BC-%EA%B3%84%EC%95%BD%EA%B0%80%EC%A1%B1%EC%9D%B4-%EB%90%98%EC%97%88%EB%8B%A4/2745',
    img: '//dn-img-page.kakao.com/download/resource?kid=Kv3Lg/hyZIeKx1gE/zXQEkaW8VNkhlVnS2qSAp0&filename=o1',
    service: 'kakao',
    searchKeyword: '바세이렌악당과계약가족이되었다생얌포야설이수',
    genre: ['로맨스', '판타지'],
    day: 'mon',
  },
  {
    webtoonId: 2589,
    title: '대사형 선유',
    author: '노경찬, 박창환',
    des: '삼류 낭인 곽노의 손에 거둬진 아이들.사제관계를 맺고 아이들은 어설프게나마무공과 보법 수련을 하며 각자의 꿈을 꾼다.먹고살기 위해 곽노는 늘 자리를 비워야 했고,아이들 중 맏이인 선유는 사제들을 돌봐야 한다.그는 대사형大師兄이다.',
    url: 'https://webtoon.kakao.com/content/%EB%8C%80%EC%82%AC%ED%98%95-%EC%84%A0%EC%9C%A0/2589',
    img: 'https://dn-img-page.kakao.com/download/resource?kid=WMpi1/hzKk16STAL/gPO8KnMnKQFRNEkgvIm7A1&filename=o1',
    service: 'kakao',
    searchKeyword: '대사형선유노경찬,박창환',
    genre: ['액션', '무협'],
    day: 'mon',
  },
  {
    webtoonId: 2043,
    title: '무지개다리 파수꾼',
    author: '이서',
    des: '돈과 성공만을 전부로 알던 유명 수의사 이한철.그는 어느 날 사고 이후,동물들의 목소리를 들을 수 있게 된다.그렇게 동물 병원을 찾은 여러 동물들의 이야기를 듣던 어느 날,길에서 만난 강아지 밍구의 살려달라는 목소리를 듣게 되는데..동물의 목소리를 듣는 수의사 이한철,동물을 사랑하는 수의 테크니션 김나영,한철의 뒷조사를 하는 동물 뉴스 플랫폼의 기자 이동욱.그리고 꼬리 달린 웰시코기 밍구와 수많은 동물들의 이야기..!',
    url: 'https://webtoon.kakao.com/content/%EB%AC%B4%EC%A7%80%EA%B0%9C%EB%8B%A4%EB%A6%AC-%ED%8C%8C%EC%88%98%EA%BE%BC/2043',
    img: '//dn-img-page.kakao.com/download/resource?kid=HAOQy/hzab4Yoymm/PdriOCx9FRGe9IOGkBLcB0&filename=o1',
    service: 'kakao',
    searchKeyword: '무지개다리파수꾼이서',
    genre: ['판타지', '드라마'],
    day: 'mon',
  },
  {
    webtoonId: 2473,
    title: '이번 생은 가주가 되겠습니다',
    author: 'ANTSTUDIO, 몬(ANTSTUDIO), 김로아',
    des: '…한번 해 보자. 내가 가주가 되는 거야.” 제국에서 제일가는 가문, 롬바르디의 사생아로 환생한 피렌티아. 게다가 이 가문은 막대한 부는 물론 외교와 문화까지 통달한 말그대로 제국의 역사 자체! 금수저 오브 금수저 인생 당첨! 앞으로는 탄탄대로일 거라 생각했는데…. 아버지는 돌아가시고, 친척들은 문전박대, 거기다 그 잘나가던 가문까지 쫄딱 망해 버릴 줄이야!! 분통을 터트리며 술을 조금(?) 많이 마시며 돌아가는 길, 마차에 치여버리기까지! “이건 해도 해도 너무하잖아….” 하지만 원망도 잠시, 눈을 뜨니 일곱 살로 돌아왔다?! 사랑하는 아버지를 다시 보는 것도 믿기지 않는데, 내가 아버지와 가문을 살릴 수도 있다고? 거기다 회귀 전 가문의 원수, 2황자가 대형견마냥 졸졸 쫓아다니기까지?! 좋아, 이렇게 된 거 2황자도 가문도 다 내 거다! 환생에 회귀까지, 인생 3회차 피렌티아의 가주되기 프로젝트!',
    url: 'https://webtoon.kakao.com/content/%EC%9D%B4%EB%B2%88-%EC%83%9D%EC%9D%80-%EA%B0%80%EC%A3%BC%EA%B0%80-%EB%90%98%EA%B2%A0%EC%8A%B5%EB%8B%88%EB%8B%A4/2473',
    img: '//dn-img-page.kakao.com/download/resource?kid=bXtxpT/hzN2hYnygX/dIpdFOEOrYAyfehnSQ8EG0&filename=o1',
    service: 'kakao',
    searchKeyword: '이번생은가주가되겠습니다ANTSTUDIO몬ANTSTUDIO김로아',
    genre: ['로맨스', '판타지'],
    day: 'mon',
  },
  {
    webtoonId: 818,
    title: '미생',
    author: '윤태호',
    des: '자신의 삶을 승리하기 위해 한 수 한 수 돌을 잇는 사람들의 이야기',
    url: 'https://webtoon.kakao.com/content/%EB%AF%B8%EC%83%9D/818',
    img: '//dn-img-page.kakao.com/download/resource?kid=8sJcC/hzacfeqPQy/XUj7WIrAOnHfIEBBuqLbq0&filename=o1',
    service: 'kakao',
    searchKeyword: '미생윤태호',
    genre: ['드라마'],
    day: 'mon',
  },
  {
    webtoonId: 1998,
    title: '사랑하는 존재',
    author: '향유 크리에이티브',
    des: '육상 유망주였으나 급성 심장병으로 모든 것을 잃은 소유.시한부를 선고받지만 기적적으로 심장을 기증받아 살아난다.쌓아왔던 것을 모두 잃어버리고 또래보다 1년 늦게 고등학교로 복귀하지만친구 관계도 꿈을 찾기도 쉽지는 않다.그러다 2학년 새 학기, 교실에서 어떤 남자애를 보는 순간 갑자기 심장이 뛰고, 눈물이 날 것 같은데...그날 밤 꿈에 만난 아저씨는자신이 바로 이식받은 심장의 주인이자 오늘 처음 본 남자애의 아빠라고 소개하는 것이 아닌가?아저씨의 아들인 재하는 가족을 모두 잃고 이 세상에 혼자라고...소유는 아저씨의 부탁에 재하에게 응원의 메시지를 건네고,행동 하나하나로 텅 빈 소유의 삶에 소중한 사람들이 생겨난다.삶의 이유, 관계, 꿈.소유는 느리지만 하나둘씩 살아가는 방법을 배워나간다.',
    url: 'https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998',
    img: '//dn-img-page.kakao.com/download/resource?kid=VMRMx/hzMUaNxocd/iIxa8HAiWrkoRHmsOFDio1&filename=o1',
    service: 'kakao',
    searchKeyword: '사랑하는존재향유크리에이티브',
    genre: ['로맨스'],
    day: 'tue',
  },
  {
    webtoonId: 2340,
    title: '도굴왕',
    author: '윤쓰(Redice Studio), 3B2S, 산지직송',
    des: '현대에 출몰한 신의 무덤.유물로 영웅의 능력을 쓰게 된 사람들, 부를 얻게 된 사람들. 그리고 그 유물을 털어가는 의문의 도굴꾼이 나타났다. 도굴왕. "아이씨, 미치겠네. 여기도 또 그자식이 다 털어 갔냐!" 네 것도 내 것. 내 건 당연히 내 것.다시 살아난 도굴꾼, 그가 세상 모든 무덤을 접수하기 시작한다!',
    url: 'https://webtoon.kakao.com/content/%EB%8F%84%EA%B5%B4%EC%99%95/2340',
    img: '//dn-img-page.kakao.com/download/resource?kid=s7mSk/hzwBkFrqoQ/vUSNxWqp98tQGq44as2D2k&filename=o1',
    service: 'kakao',
    searchKeyword: '도굴왕윤쓰RediceStudio3B2S산지직송',
    genre: ['학원', '판타지'],
    day: 'tue',
  },
  {
    webtoonId: 1369,
    title: '지옥사원',
    author: '네온비, 캐러멜',
    des: '인간의 음식에 매료된 악마 쿼터,사고로 흙수저 인간에게 빙의하다?!능력을 모두 잃고 인간 <고순무>의 몸에 갇힌 악마는, ‘낮은 등급’ 인간의 삶이 지옥에서의 삶보다 질이 떨어지자 ‘높은 등급’ 인간이 되기로 결심한다. 한 편, 국내 최고의 대기업 <선호 그룹>에선 학력과 경력을 보지 않는 특별 신입 사원 채용이 열리고, 악마는 식품 사업의 말단 직원으로 입사하는데…회사원이 된 악마는 무엇을 얻어가고, 주변 인간들에게 어떤 영향을 끼치게 될까?“인간처럼 생각해서 정답이 안 나올 땐, 악마처럼 행동해. 회사는 그걸 더 좋아할 거야!”세상의 부조리함을 위트 있고 날카롭게 파고드는 판타지 드라마!',
    url: 'https://webtoon.kakao.com/content/%EC%A7%80%EC%98%A5%EC%82%AC%EC%9B%90/1369',
    img: '//dn-img-page.kakao.com/download/resource?kid=d8db3i/hyfOB3WBxC/dJq9oY5Ha6LbuBnrtES1Sk&filename=o1',
    service: 'kakao',
    searchKeyword: '지옥사원네온비캐러멜',
    genre: ['판타지', '드라마'],
    day: 'tue',
  },
  {
    webtoonId: 3299,
    title: '도망쳤더니 결혼을 하게 됐습니다',
    author: '스튜디오 늘봄, 토란, 은솔림',
    des: '더는 지옥에서 살고 싶지 않아.”바꿀 거야 내 인생을, 내가 있어야 할 자리를! 후원자 ‘유리’에게 자신의 특별한 능력 ‘언령술’을 착취당하고 이용만 당하다 죽은 ‘라피아’.고통스러운 삶에서 해방되어 그토록 원하던 안식을 얻었다고 생각한순간, 눈을 떠보니 유리를 처음 만난 9년 전으로 돌아왔다.지옥 같은 삶을 되풀이 하고 싶지 않은 라피아는 전생에서 유리와 대적하던  ‘카세인’의 가문 솔레이아 공작가로 도망쳐 새로운 후원 계약을 한다. 그런데 놀랍게도 후원 계약의 내용이 카세인과의 결혼…?? "도망쳤더니 결혼을 하게 됐습니다??!"',
    url: 'https://webtoon.kakao.com/content/%EB%8F%84%EB%A7%9D%EC%B3%A4%EB%8D%94%EB%8B%88-%EA%B2%B0%ED%98%BC%EC%9D%84-%ED%95%98%EA%B2%8C-%EB%90%90%EC%8A%B5%EB%8B%88%EB%8B%A4/3299',
    img: '//dn-img-page.kakao.com/download/resource?kid=4FSxL/hzVqIVF72y/x0CHQX6NRsAn7fYGuis4m1&filename=o1',
    service: 'kakao',
    searchKeyword: '도망쳤더니결혼을하게됐습니다스튜디오늘봄토란은솔림',
    genre: ['로맨스', '판타지'],
    day: 'tue',
  },
  {
    webtoonId: 2871,
    title: '튜린의 릴리엔',
    author: '나겸, 나유혜',
    des: '원작 남주인공의 트라우마를 담당하는 나쁜 엄마가 되긴 싫었다. 평안한 인생 설계를 위해서 오빠와의 관계도 잘 다져놓고 남편이 흑화하지 않도록 충실히 의무를 다하기로 했을 뿐인데.... 남편이 갑자기 달콤하게 굴기 시작했다.',
    url: 'https://webtoon.kakao.com/content/%ED%8A%9C%EB%A6%B0%EC%9D%98-%EB%A6%B4%EB%A6%AC%EC%97%94/2871',
    img: '//dn-img-page.kakao.com/download/resource?kid=t0ZHa/hzVqFdtG0w/Hyo8HdM4MHQPr4d0EJd2G0&filename=o1',
    service: 'kakao',
    searchKeyword: '튜린의릴리엔나겸나유혜',
    genre: ['로맨스', '판타지'],
    day: 'tue',
  },
  {
    webtoonId: 3266,
    title: '벼락승진',
    author: '이모세',
    des: '야근과 주말 출근이 일상인 광고대행사 [페퍼기획]두 달간 하루도 쉬지 못한 제작 3팀은오늘도 고군분투 중이다.워라밸이 최우선인 MZ세대 박대희 사원회사와 일이 최우선인 기성세대 전영규 팀장서로가 너무 달라 서로를 이해할 수 없었던 두 사람이서로의 몸이 바뀌게 되면서 서로를 연기하기 시작한다.',
    url: 'https://webtoon.kakao.com/content/%EB%B2%BC%EB%9D%BD%EC%8A%B9%EC%A7%84/3266',
    img: '//dn-img-page.kakao.com/download/resource?kid=cY4Ulb/hzR1R2Xlfz/lQHEaDyP2sE5DQsHJMahh0&filename=o1',
    service: 'kakao',
    searchKeyword: '벼락승진이모세',
    genre: ['드라마'],
    day: 'tue',
  },
  {
    webtoonId: 2485,
    title: '다정한 그대를 지키는 방법',
    author: '하운드, 김지의, 마약젤리',
    des: '나를 증오하는 남자와 결혼하게 되었다. 나의 어머니가 그의 가족들을 죽였으니, 당연한 일이었다. “결혼 전에 꼭 약속해 주셨으면 하는 게 있어요 반년 후엔, 이혼해 주셨으면 해요.” “……네?” “억지로 하는 결혼이잖아요. 원치 않는 결혼을 굳이 이어 갈 필요 없다고 생각해요.” “원치 않는, 결혼이요.” 그는 멍하니 나의 말을 반복했다.',
    url: 'https://webtoon.kakao.com/content/%EB%8B%A4%EC%A0%95%ED%95%9C-%EA%B7%B8%EB%8C%80%EB%A5%BC-%EC%A7%80%ED%82%A4%EB%8A%94-%EB%B0%A9%EB%B2%95/2485',
    img: '//dn-img-page.kakao.com/download/resource?kid=cGYGI/hyRyOfdcsO/AapDpIrzAITKHe62Rk1eeK&filename=o1',
    service: 'kakao',
    searchKeyword: '다정한그대를지키는방법하운드김지의마약젤리',
    genre: ['로맨스', '판타지'],
    day: 'tue',
  },
  {
    webtoonId: 2362,
    title: '북검전기',
    author: '해민, 우각',
    des: '무협소설의 최강자 우각의 동명 소설 <북검전기>가 만화로 새롭게 태어나다! 세상을 혼란에 빠뜨린 집단 밀야에 맞서기 위해 중원의 고수들이 모여 만들어낸 북천문!북천문의 강력한 투쟁으로 밀야는 서서히 그 모습을 감추었고, 북천문은 중원을 평화를 대표하는 집단으로서 강력한 위용을 과시하게 되었다.그러나 평화가 길어지자 중원의 고수들 사이에서는 북천문에 대한 은밀한 시기가 생겨났고, 결국 북천문의 4대 문주인 진관호는 배신자들에게 둘러싸인 채 스스로 목숨을 끊음으로서 파국의 끝을 맞이하게 된다. 모두가 떠난 북천문에 홀로 남은 진관호의 아들 진무원(13세)은 무공이라고는 손톱만큼도 알지 못 하는 어린 소년. 그러나 남몰래 아버지가 전수한 고어(古語)를 통해 북천문의 벽에 새겨진 무공을 익히기 시작한다. 그러던 어느날, 진무원의 앞에 정체를 알 수 없는 한 소녀가 나타나게 되는데…!!',
    url: 'https://webtoon.kakao.com/content/%EB%B6%81%EA%B2%80%EC%A0%84%EA%B8%B0/2362',
    img: '//dn-img-page.kakao.com/download/resource?kid=MwMMk/hyzT0qjxuu/gZIHDDx6unI9OGiunCkD4K&filename=o1',
    service: 'kakao',
    searchKeyword: '북검전기해민우각',
    genre: ['액션', '무협'],
    day: 'wed',
  },
  {
    webtoonId: 3211,
    title: '무한의 마법사',
    author: 'kiraz(REDICE STUDIO), 테미스, 김치우',
    des: '마굿간에 버려져 평민으로 키워진 아이, 시로네. 타고난 통찰력으로 글까지 깨우친 아이는도시로 나간 어느 날 그토록 궁금해하던 마법을 경험한다. 그 길로 마법사를 꿈꾸게 된 시로네.하지만 신분의 장벽이 두터운 이 곳은 아이에게 냉혹하고,그는 채 어른이 되기도 전에 이 세상의 이면을 알아버리는데···. 어딘가 비틀어진 이 세계에서그는 자신이 꿈꾸던 마법사가 될 수 있을까?',
    url: 'https://webtoon.kakao.com/content/%EB%AC%B4%ED%95%9C%EC%9D%98-%EB%A7%88%EB%B2%95%EC%82%AC/3211',
    img: '//dn-img-page.kakao.com/download/resource?kid=bbXpgU/hyoXzXU0Zn/y5Ae8SzxX1EorWXZH6Ez90&filename=o1',
    service: 'kakao',
    searchKeyword: '무한의마법사kirazREDICESTUDIO테미스김치우',
    genre: ['학원', '판타지'],
    day: 'wed',
  },
  {
    webtoonId: 3024,
    title: '여보, 나 파업할게요',
    author: '송예슬, 고은채',
    des: '시몬 제국의 백작 영애 카시아 루베르노는황제의 명으로 평민 출신의 전쟁영웅 제스터 그레제와 결혼하지만10년 간 사랑도, 돈도 없이 힘들게만 살다 불치병으로 죽게 된다.아니, 죽은 줄로만 알았다. 죽음과 동시에 10년 전 그레제에 온 첫날로 회귀한 그녀는전과 같은 삶을 반복하지 않기 위해 ‘파업’을 선언한다.무뚝뚝하고 전쟁밖에 모르던 남편 제스터는 계속해서 카시아의 마음에 다가오려 노력하는데...이러한 제스터의 노력과 변화가 이상하면서도 싫지만은 않았던 카시아는,어쩌면 이번 생을 바꿀 수 있을 지도 모른다는 생각을 갖게 된다.',
    url: 'https://webtoon.kakao.com/content/%EC%97%AC%EB%B3%B4-%EB%82%98-%ED%8C%8C%EC%97%85%ED%95%A0%EA%B2%8C%EC%9A%94/3024',
    img: '//dn-img-page.kakao.com/download/resource?kid=dMliN/hzMT7DkIhv/KE0JUAz80a2ax3ZAAZxwDk&filename=o1',
    service: 'kakao',
    searchKeyword: '여보,나파업할게요송예슬고은채',
    genre: ['로맨스', '판타지'],
    day: 'wed',
  },
  {
    webtoonId: 2494,
    title: '장르를 바꿔보도록 하겠습니다',
    author: '가린, KEN',
    des: '좋아했던 장르 소설 속에 빙의했다. 하필이면 어린 주인공을 학대하는 악역 이모로. 복수극의 주인공으로 자라날 조카가 안쓰러워   원작대로, 삼촌이 나타나 조카를 데려갈 때까지만이라도 살뜰히 보살피려 노력했다. 그랬더니... "어, 엄마!" 졸지에 애엄마가 되어버렸다?!  "사정이 어떻게 되신 건지는 모르겠습니다만, 모자지간을 어떻게 찢어두겠습니까? 숙녀분도 함께 빈터발트로 가시지요." 야, 김루카! 이 오해는 어떻게 풀어줄 건데!',
    url: 'https://webtoon.kakao.com/content/%EC%9E%A5%EB%A5%B4%EB%A5%BC-%EB%B0%94%EA%BF%94%EB%B3%B4%EB%8F%84%EB%A1%9D-%ED%95%98%EA%B2%A0%EC%8A%B5%EB%8B%88%EB%8B%A4/2494',
    img: '//dn-img-page.kakao.com/download/resource?kid=qFSyq/hzp2mwlI2m/0jFJ8u1P5aG8HAYMSoJYTk&filename=o1',
    service: 'kakao',
    searchKeyword: '장르를바꿔보도록하겠습니다가린KEN',
    genre: ['로맨스', '판타지'],
    day: 'wed',
  },
  {
    webtoonId: 3334,
    title: '진짜 딸이 돌아왔다',
    author: '린아, 마루코믹스',
    des: "천한 하녀의 피를 물려받은 반쪽짜리 귀족, 헬가 유트리트.하녀가 바꿔치기한 공작가의 사생아, 가짜 딸.헬가는 진짜가 되기 위해 노력하고 또 노력했다.'공작부인! 진짜 공녀님이 살아있답니다.''이름은 힐리안느라고…!'진짜가 돌아와 헬가의 자리를 빼앗지 않게 해달라고 신께 빌고 또 빌었다.'…지마. 힐리안느''돌아오지 마, 제발.'가짜가 한 기도라서 신께 닿지 않았던 걸까.'신이시여. 그동안 수도 없이 빌었잖아.''그 애가 돌아오지 못하게 해달라고.'목이 쉬어라 외쳤던 기도들이 무색하게도 결국 돌아왔다.내 세상을 전부 무너트릴 그 아이…공작가의 진짜 딸, 힐리안느.진짜 딸이 돌아왔다.",
    url: 'https://webtoon.kakao.com/content/%EC%A7%84%EC%A7%9C-%EB%94%B8%EC%9D%B4-%EB%8F%8C%EC%95%84%EC%99%94%EB%8B%A4/3334',
    img: '//dn-img-page.kakao.com/download/resource?kid=bhagt0/hzCs7tog59/s7dGKKLNrJEocfh2VqhYc0&filename=o1',
    service: 'kakao',
    searchKeyword: '진짜딸이돌아왔다린아마루코믹스',
    genre: ['로맨스', '판타지'],
    day: 'wed',
  },
  {
    webtoonId: 1525,
    title: '경이로운 소문',
    author: '장이',
    des: '영원불멸의 삶을 위해 지구로 내려온 사후세계 악한 영혼들. 그들을 잡는 카운터들의 이야기.',
    url: 'https://webtoon.kakao.com/content/%EA%B2%BD%EC%9D%B4%EB%A1%9C%EC%9A%B4-%EC%86%8C%EB%AC%B8/1525',
    img: 'https://dn-img-page.kakao.com/download/resource?kid=dRP8hq/hyLjhgB9xQ/vKQdRtLyxKQTm46m3oJrCk&filename=th3',
    service: 'kakao',
    searchKeyword: '경이로운소문장이',
    genre: ['판타지', '드라마'],
    day: 'thu',
  },
  {
    webtoonId: 1796,
    title: '샬롯에게는 다섯 명의 제자가 있다',
    author: '용용',
    des: '세상을 구한 위대한 대마법사 〈샬롯 엘레노어〉생애 마지막 마법을 시전하고 눈을 감는다.하지만 이게 웬일?다시 눈을 떠보니 뜬금없이 어린아이가 되어버렸다!마법은 스스로의 마음에서 시작되고 그 바람을 이루어 주는 것.죽음을 앞둔 샬롯의 유일한 아쉬움은 바로… 「사랑」?!고되었던 대마법사의 삶과 다섯 제자들을 뒤로하고 "아리아 리센"이란 이름으로 제2의 삶을 살아가기로 한다.하지만 자신이 사라진 이후 제자들의 행적에 대한 소문들이 심상치 않은데…?스승님만을 찾아 헤매는 다섯 제자들과 다시금 드리우는 재앙의 그림자.…샬롯은 과연 사랑을 찾을 수 있을까? ',
    url: 'https://webtoon.kakao.com/content/%EC%83%AC%EB%A1%AF%EC%97%90%EA%B2%8C%EB%8A%94-%EB%8B%A4%EC%84%AF-%EB%AA%85%EC%9D%98-%EC%A0%9C%EC%9E%90%EA%B0%80-%EC%9E%88%EB%8B%A4/1796',
    img: '//dn-img-page.kakao.com/download/resource?kid=bL3rA1/hzCtfLuPpt/2m7NgLcWqInXOhUJnRpUbk&filename=o1',
    service: 'kakao',
    searchKeyword: '샬롯에게는다섯명의제자가있다용용',
    genre: ['로맨스', '판타지'],
    day: 'thu',
  },
  {
    webtoonId: 2155,
    title: '관존 이강진',
    author: '노경찬, 송윤달',
    des: '미친놈인가?아니면 흔한 관심종자인가?사람의 다름을 이해 못 하는 제자 이강진.그리고 그걸 이해시켜주고자 하는 스승 곽노.두 사제師弟의 따뜻한 휴먼스토리.',
    url: 'https://webtoon.kakao.com/content/%EA%B4%80%EC%A1%B4-%EC%9D%B4%EA%B0%95%EC%A7%84/2155',
    img: '//dn-img-page.kakao.com/download/resource?kid=ATKSq/hzKkYnQece/oReiJxjMDjqtHvI1n06pr0&filename=o1',
    service: 'kakao',
    searchKeyword: '관존이강진노경찬송윤달',
    genre: ['액션', '무협'],
    day: 'thu',
  },
  {
    webtoonId: 2472,
    title: '아빠, 나 이 결혼 안 할래요!',
    author: '유리, Roal, 홍희수',
    des: '모두에게 미움받는 악녀 "쥬벨리안."사랑했던 애인도 단 하나뿐인 가족, 아버지에게도 버림받고 쓸쓸히 죽어버린 비참한 악역…쥬벨리안이 바로 나라고?인생 2회차 이렇게 된 이상 사랑받는 건 텄다!아버지의 돈으로 꿀이나 빨겠어!화려한 공녀라이프를 선언했건만, 아니, 아버지! 싸이코패스 황태자가 제 결혼 상대라고요?방법은 단 하나, 계약 연애뿐!그리고 상대로는 아버지의 제자가 좋겠다고 결론 내린다. 바로 그 남자가 황태자인 줄 모른 채….',
    url: 'https://webtoon.kakao.com/content/%EC%95%84%EB%B9%A0-%EB%82%98-%EC%9D%B4-%EA%B2%B0%ED%98%BC-%EC%95%88-%ED%95%A0%EB%9E%98%EC%9A%94/2472',
    img: '//dn-img-page.kakao.com/download/resource?kid=dpaXV0/hyRyPE9lgT/vIH8TgqjfiGZunvrwZ0kiK&filename=o1',
    service: 'kakao',
    searchKeyword: '아빠,나이결혼안할래요!유리Roal홍희수',
    genre: ['로맨스', '판타지'],
    day: 'thu',
  },
  {
    webtoonId: 3224,
    title: '버린 쓰레기는 다시 줍지 않는다',
    author: '티바, 버텍스, 배고픈밤',
    des: '6년 만에 전쟁에서 돌아온 약혼자 품에 안긴 다른 여자,심지어 그 여자가 임신을 하고 있다면 어떻게 해야할까?"네가 시험에 통과하지 못하면, 그녀에게 사과해!""시녀들과 신분이 비슷한 영애한테 부탁하는 거예요."내연녀만을 애지중지하며 자신을 홀대하는 약혼자와순진한 척하며 자신을 괴롭히는 악녀에 지친 레일라.공작부인이라는 길로 밖에 집에서 탈출할 수 없었던 그녀는,낯선 남자의 제안에 끌려 황제 보좌관 시험에 도전한다."축하한다, 테베사 영애.""당신은…."그리고 그 끝에서 레일라를 기다리고 있던 것은그 때 그 낯선 남자."폐, 폐하…!"바로 황제였다.',
    url: 'https://webtoon.kakao.com/content/%EB%B2%84%EB%A6%B0-%EC%93%B0%EB%A0%88%EA%B8%B0%EB%8A%94-%EB%8B%A4%EC%8B%9C-%EC%A4%8D%EC%A7%80-%EC%95%8A%EB%8A%94%EB%8B%A4/3224',
    img: '//dn-img-page.kakao.com/download/resource?kid=gNY7V/hzKkZtydu2/K6QykvmGP9tKuUKWkLifeK&filename=o1',
    service: 'kakao',
    searchKeyword: '버린쓰레기는다시줍지않는다티바버텍스배고픈밤',
    genre: ['로맨스', '판타지'],
    day: 'thu',
  },
  {
    webtoonId: 2327,
    title: '신마경천기',
    author: '곰국, 일황',
    des: '"평생 협의를 외치셨던 분이 이리 가셨습니까…!"  금지된 마공을 익혔다는 누명을 쓰고 죽임 당한 창존문의 계승자와 제자 혁운성.  정파의 위선자들에 의한 비참하고 억울한 죽음…   운성이 죽음을 맞이하는 순간,  창존문의 신물이 빛을 발하며 새로운 인생이 주어진다.   바로, 마교 수련생 구백 호로서의 인생이!   정파와 마교, 두 개의 정체성. 그러나 목표는 하나, 복수뿐!   운명을 받아들이고 원한을 되씹으며 운성은 무공을 쌓고 그렇게 복수의 시간도 차츰 다가오는데….   마교를 장악하고 정파의 위선자들을 처단하라! 생사를 건 난관 속에 성장하는 구백 호 운성의 복수 활극!',
    url: 'https://webtoon.kakao.com/content/%EC%8B%A0%EB%A7%88%EA%B2%BD%EC%B2%9C%EA%B8%B0/2327',
    img: '//dn-img-page.kakao.com/download/resource?kid=lkOY6/hzhOfSaR8s/Sgjeqz1qicZI2r9CVbWIMK&filename=o1',
    service: 'kakao',
    searchKeyword: '신마경천기곰국일황',
    genre: ['액션', '무협'],
    day: 'thu',
  },
  {
    webtoonId: 3014,
    title: '무적자',
    author: '노경찬, 휘',
    des: '임화평.이름처럼 평범하게 살고 싶었던 사내.그랬던 그의 모든 것이 파괴되었다.[너희들의 사랑이 내게는 증오가 되었구나.]건드리지 말았어야지.조용히 그렇게 살게 놔뒀어야지.그 어떠한 적籍도 두지 못하게 돼버린 그가 움직이기 시작한다. ',
    url: 'https://webtoon.kakao.com/content/%EB%AC%B4%EC%A0%81%EC%9E%90/3014',
    img: '//dn-img-page.kakao.com/download/resource?kid=vl8Xp/hzab9edf2b/Mx6tZ7vhS2SnJQF7rPCKc1&filename=o1',
    service: 'kakao',
    searchKeyword: '무적자노경찬휘',
    genre: ['액션', '무협'],
    day: 'fri',
  },
  {
    webtoonId: 2335,
    title: '두 번 사는 랭커',
    author: '농농, 사도연',
    des: '5년 전 사라진 쌍둥이 동생을 잊고 살던 연우.어느날 그에게 동생의 유품인 회중시계가 돌아왔다. 그리고 그 속에 숨겨진 일기장. "형이 이 일기를 들을 때 즈음이라면 나는 이미 이 세상 사람이 아니겠지." 여러 차원과 우주가 교차하는 세계에 놓인 태양의 신 탑, 오벨리스크.그리고 그곳에 오르다 배신당해 눈을 감아야 했던 동생. 모든 걸 알게 된 연우는 동생이 남겨 둔 일기와 함께 탑을 오르기 시작한다. "오늘부터 난. 차정우이다."',
    url: 'https://webtoon.kakao.com/content/%EB%91%90-%EB%B2%88-%EC%82%AC%EB%8A%94-%EB%9E%AD%EC%BB%A4/2335',
    img: '//dn-img-page.kakao.com/download/resource?kid=ddrgS/hyLjfQWY6S/D26IDY6gJ1ZWbadeOQTUnK&filename=o1',
    service: 'kakao',
    searchKeyword: '두번사는랭커농농사도연',
    genre: ['학원', '판타지'],
    day: 'fri',
  },
  {
    webtoonId: 3259,
    title: '여주인공이 나를 새언니로 점찍었다',
    author: '연견, 겨울해, 채유화',
    des: '빨간망토가 늑대를 잡아먹는 19금 피폐 여공남수 소설에 빙의했다. 문제는 그 늑대가 바로 내 남동생이란 사실! 동생과 깊은 숲속에 숨어 인간계로 도망갈 계획을 세우던 중, 눈밭에 쓰러진 여자아이를 발견했다. 아픈 아이를 지나칠 수 없어 지극정성으로 보살폈건만, 이 아이... 하필이면 최종흑막, 빨간망토잖아?! 치료를 마치는 대로 어서 돌려보내야지 다짐하기도 잠시, "언니는 이상형이 어떻게 돼요?" "언니는 키 크고 어깨 넓은 남자를 좋아하는구나." 어쩐지 아이가 날 바라보는 눈빛이 심상치 않다. 유독 이상형 이야기를 할 때 눈이 초롱초롱해지는 건 내 착각이겠지? 나.... 동생이랑 같이 얼른 도망쳐야 하는데.... "우리 오빠 잘생겼죠?" 여기서 갑자기 왜 네 오빠가 나와?!',
    url: 'https://webtoon.kakao.com/content/%EC%97%AC%EC%A3%BC%EC%9D%B8%EA%B3%B5%EC%9D%B4-%EB%82%98%EB%A5%BC-%EC%83%88%EC%96%B8%EB%8B%88%EB%A1%9C-%EC%A0%90%EC%B0%8D%EC%97%88%EB%8B%A4/3259',
    img: '//dn-img-page.kakao.com/download/resource?kid=cVunjH/hyRyP6lVmt/CvnTLGqrQkcBPvCGVYjKM1&filename=o1',
    service: 'kakao',
    searchKeyword: '여주인공이나를새언니로점찍었다연견겨울해채유화',
    genre: ['로맨스', '판타지'],
    day: 'fri',
  },
  {
    webtoonId: 2383,
    title: '악역의 엔딩은 죽음뿐',
    author: '수월, 권겨을',
    des: '역하렘 공략 게임의 악역,  에카르트 공작가의 하나뿐인 공녀이자 입양아 페넬로페로 빙의했다.   그런데 하필 난이도는 극악!  뭘 해도 엔딩은 죽음뿐!   ‘진짜 공녀’가 나타나기 전에 여주의 어장 중 한 명을 공략해서 살아남아야 한다.  사사건건 시비를 거는 오빠 1, 2. 모든 루트가 죽음으로 이어지는 미친 황태자. 여주바라기 마법사와 충직한 노예 기사까지!  ‘일단 가망성 없는 놈들은 바로 버리자.’  “그동안 제 주제를 잘 몰랐어요. 앞으로는 쭉, 신경 쓰실 일 없이, 쥐죽은 듯 살겠습니다.”  근데 왜 자꾸 선을 그을수록 호감도가 오르는 거야?! 악역 페넬로페의 미친 역하렘 공략 게임 생존기!',
    url: 'https://webtoon.kakao.com/content/%EC%95%85%EC%97%AD%EC%9D%98-%EC%97%94%EB%94%A9%EC%9D%80-%EC%A3%BD%EC%9D%8C%EB%BF%90/2383',
    img: '//dn-img-page.kakao.com/download/resource?kid=dteRzY/hzwBpGAxpD/Al437v8aDUThHVw0sd2A7k&filename=o1',
    service: 'kakao',
    searchKeyword: '악역의엔딩은죽음뿐수월권겨을',
    genre: ['로맨스', '판타지'],
    day: 'fri',
  },
  {
    webtoonId: 3322,
    title: 'VR히어로',
    author: '백민기',
    des: '현실에서는 매우 어렵게 살아가는 주인공, 가상 세계인 비트월드에 접속하게 된 후 그의 인생이 180도 바뀌게 된다.뜻밖에 얻은 무기로 인해 최강자가 되어 많은 인기와 부를 얻게 되어 행복한 나날을 보내지만, 사실 만재는 엄청난 대가를 치르고 있었다. 강함과 죄책감 그 거부할 수 없는 관계 속에서 과연 주인공은 어떻게 될 것인지...당신이라면 과연 어떤 선택을 할 것인가',
    url: 'https://webtoon.kakao.com/content/VR%ED%9E%88%EC%96%B4%EB%A1%9C/3322',
    img: 'https://dn-img-page.kakao.com/download/resource?kid=hF5sE/hzVqEyPsiO/6Zao5onsmaHtLgB6gRMeZ1&filename=o1',
    service: 'kakao',
    searchKeyword: 'VR히어로백민기',
    genre: ['학원', '판타지'],
    day: 'fri',
  },
  {
    webtoonId: 2141,
    title: '백작가의 불청객들',
    author: '아르누니',
    des: "스캔들이 많고 교양 없기로 유명한 '필데트 백작가'.백작 부부는 유서 깊은 가문의 명예를 깎아먹는 주범이지만,다행히 이들 부부의 영특하고 사랑스러운 외아들, '헤이든' 덕분에 필데트 백작가는 그럭저럭 평화를 유지하고 있다.헤이든은 백작가의 체면을 세워주는 자랑거리인 동시에,틈만 나면 서로 으르렁거리는 백작 부부의 유일한 연결 고리이자 평화의 구심점이다.하지만 헤이든이 만든 평화는 깊은 수심을 가리는 얇은 얼음 장막에 불과하다.그 이면에는 케케묵은 오해와 불신, 그리고 말할 수 없는 비밀이 아득한 어둠 속에 퇴적되어 있기에...그러던 어느 날, 갑작스럽게 찾아온 불청객들이 얼음 장막 위를 걸어가는데?!서서히 금이 가는 이들의 평화!백작가는 불편한 진실을 마주하며 갈등하지만,오해의 퇴적물 속에는 서로를 소중히 여기는 마음도 보물처럼 함께 있음을 깨닫는다.오해를 딛고 불완전한 서로를 보듬고함께 성장하는 가족의 이야기.",
    url: 'https://webtoon.kakao.com/content/%EB%B0%B1%EC%9E%91%EA%B0%80%EC%9D%98-%EB%B6%88%EC%B2%AD%EA%B0%9D%EB%93%A4/2141',
    img: '//dn-img-page.kakao.com/download/resource?kid=3R2wb/hzp2kLWfEt/i1cVG8rY1or1UxRfmVF36k&filename=o1',
    service: 'kakao',
    searchKeyword: '백작가의불청객들아르누니',
    genre: ['드라마'],
    day: 'sat',
  },
  {
    webtoonId: 3281,
    title: '가짜를 위한 장소는 없다',
    author: '로고,오앤',
    des: '어미와 공모하여 황녀를 사칭하고,  마탑과 제국을 이간질하여 전쟁을 일으킨 "가짜 황녀", 필로멜. 그녀는 모든 죄가 들통나자 사형 당한다. 실로 악당에 어울리는...... "내가, 아니 책 속의 필로멜이 잘못을 했기로서니 죽일 만큼은 아니잖아!" 필로멜은 괴성을 지르며 읽던 책을 던졌다. 정원에서 주운 수상한 책이 궁금했을 뿐인데  자신, 아니 책 속의 필로멜 황녀가 죽는다니!  허구일 뿐이라고 믿고 싶지만, 어쩐지 이후 일어나는 모든 일들은 그 책과 똑 닮아있는데. "이렇게 된 이상... 목표는 생존 뿐이야!" 과연 필로멜은 수상한 책의 정체를 밝히고 자신의 인생을 찾을 수 있을것인가.',
    url: 'https://webtoon.kakao.com/content/%EA%B0%80%EC%A7%9C%EB%A5%BC-%EC%9C%84%ED%95%9C-%EC%9E%A5%EC%86%8C%EB%8A%94-%EC%97%86%EB%8B%A4/3281',
    img: '//dn-img-page.kakao.com/download/resource?kid=Kv3Lg/hyZIeKx1gE/zXQEkaW8VNkhlVnS2qSAp0&filename=o1',
    service: 'kakao',
    searchKeyword: '가짜를위한장소는없다로고오앤',
    genre: ['로맨스', '판타지'],
    day: 'sat',
  },
  {
    webtoonId: 2315,
    title: '화산전생',
    author: '토마씨, 정준',
    des: '전란의 시대에서 운이 좋게 살아남아 화산파의 장로가 된 주서천.평생 영광을 맛보지 못한 채 후회와 미련만 가득 안고 눈을 감는다.​그러나 죽음을 맞이하는 순간, 어찌 된 영문인지 운명은 그를 다시 과거로 돌려보내는데…….',
    url: 'https://webtoon.kakao.com/content/%ED%99%94%EC%82%B0%EC%A0%84%EC%83%9D/2315',
    img: '//dn-img-page.kakao.com/download/resource?kid=Bhw9l/hzhOj1XUfE/zN2Zb5ipGewccBpvp63KY0&filename=o1',
    service: 'kakao',
    searchKeyword: '화산전생토마씨정준',
    genre: ['액션', '무협'],
    day: 'sat',
  },
  {
    webtoonId: 3261,
    title: '세계관 최강자들이 내게 집착한다',
    author: 'ZION, 김코끼리',
    des: '간식으로 나온 빵을 오물거리던 열 세살의 어느날, 달리아 페스테로즈는 문득 자신의 전생을 기억해낸다. 이곳은 주인공들이 미쳐가는 피폐 여성향 게임 속 세상이고, 자신은 장차 최고 악당의 여동생으로 태어났다는 것을! 이대로라면 답도 없다. 가문은 멸문할거고, 나도 덤으로 쓱싹 되겠지. 그러니 무조건, 가능한 한 빨리 이 가문에서 달아나야 한다! "이렇게 된 이상 경계심을 낮춰 도망쳐야겠어!" 그렇게 가문을 노리는 친척과 능구렁이 같은 황제 등등을 걷어내고 오빠의 환심을 듬뿍 산 것까지는 좋았는데- "내가 달리아와 춤을 추고 싶은데. 뭐가 문제지?""미안하지만, 내 동생이 낯을 가려서.""달리아는 제가 제일 좋다고 했어요!" 어쩐지, 오빠를 너무 길들인 것도 모자라 이 세계 최강자들이 모두 나에게 집착한다!',
    url: 'https://webtoon.kakao.com/content/%EC%84%B8%EA%B3%84%EA%B4%80-%EC%B5%9C%EA%B0%95%EC%9E%90%EB%93%A4%EC%9D%B4-%EB%82%B4%EA%B2%8C-%EC%A7%91%EC%B0%A9%ED%95%9C%EB%8B%A4/3261',
    img: '//dn-img-page.kakao.com/download/resource?kid=cADsJ6/hzCtap5hGj/8i8LbgAwQeNHrI2wTrVNuK&filename=o1',
    service: 'kakao',
    searchKeyword: '세계관최강자들이내게집착한다ZION김코끼리',
    genre: ['로맨스', '판타지'],
    day: 'sat',
  },
  {
    webtoonId: 3022,
    title: '벼락 맞을 인간들',
    author: '곽인근',
    des: '로또 단독 1등으로 270억에 당첨된주인공의 신상을 유튜버가 털어가버렸다.많은 사람들이 돈을 위해주인공을 노리는 와중에 첫사랑이 찾아온다.당첨 복권을 노리는 무수한 위협 속에서주인공은 당첨금을 찾기 위한 여정을 떠나는데...',
    url: 'https://webtoon.kakao.com/content/%EB%B2%BC%EB%9D%BD-%EB%A7%9E%EC%9D%84-%EC%9D%B8%EA%B0%84%EB%93%A4/3022',
    img: '//dn-img-page.kakao.com/download/resource?kid=dlzlN9/hzab5clZd4/wPOxTObMXkwe4o2fO29zPK&filename=o1',
    service: 'kakao',
    searchKeyword: '벼락맞을인간들곽인근',
    genre: ['드라마'],
    day: 'sat',
  },
  {
    webtoonId: 3324,
    title: '복수를 후원해 주세요',
    author: '은산, SAM, 정오찬',
    des: '유복한 에펠렌티아 백작가의 적자로 태어난 로벨리아.아버지인 제임스 에펠렌티아 백작의 죽음 이후,그녀의 불행은 시작된다. "세상은 날 버렸고, 원수는 모든 걸 송두리째 빼앗아 갔다. 어머니마저..."==어머니의 죽음 이후 알게 된 진짜 원수, 그리고 악녀로 내몰리게 될 자신의 미래."모든 것을 원래대로 되돌려야 해. 나를 악녀로 만드는 운명을 피하겠어."복수를 결심한 그녀는 위험한 조력자에게 후원을 제안하는데...과연 로벨리아는 복수를 완성할 수 있을까?=="모든 일이 끝났을 때, 그대의 옆에 있고 싶어."그리고 자신에게 구애하는 남자와행복한 결말을 맞이할 수 있을까?',
    url: 'https://webtoon.kakao.com/content/%EB%B3%B5%EC%88%98%EB%A5%BC-%ED%9B%84%EC%9B%90%ED%95%B4-%EC%A3%BC%EC%84%B8%EC%9A%94/3324',
    img: '//dn-img-page.kakao.com/download/resource?kid=8rDPH/hyoXyc5Ai3/N0nij277CV13GIedmaS1s0&filename=o1',
    service: 'kakao',
    searchKeyword: '복수를후원해주세요은산SAM정오찬',
    genre: ['로맨스', '판타지'],
    day: 'sat',
  },
  {
    webtoonId: 2511,
    title: '가드패스',
    author: '오손도손',
    des: '평소 먹는 것을 좋아해 뚱뚱하고 큰 체격을 가진 "임세준".그는 뚱보라는 놀림에도 신경 쓰지 않는자존감이 높고 확고한 성격을 가졌다.그에게 단 한 명의 친구 "서하진".그녀는 어릴 적부터 세준을 지켜주기 위해 늘 운동을 배워왔다.어느 날 세준은 같은 반 일진과 트러블이 생기고그것을 본 하진은 눈이 돌아가 일진을 박살 내게 된다.그런데 어느 날 밤 하진은 심하게 폭행당한 채로 발견되고크게 다친 무릎과 더 심각한 정신적 후유증을 얻는다.세준은 경찰에게 말해보지만 수사에 별 진척이 없자분노를 주체하지 못하고 직접 범인을 찾아 나서지만주짓수를 배운 일진에게 패배하고 아무것도 알아내지 못한다.그리곤 그를 구해준 "제이슨"이라는 사람에게주짓수를 배우게 되는데, 그렇게 3개월, 운동을 배우고 살을 뺀 세준은 일진들을 쓰러뜨려가며 베일에 싸인 한 단체가 연루되어있다는 사실을 알게 되고,그 뿌리까지 모조리 뽑아버리려 한다.개인의 복수를 그리는 학원 액션 드라마.',
    url: 'https://webtoon.kakao.com/content/%EA%B0%80%EB%93%9C%ED%8C%A8%EC%8A%A4/2511',
    img: '//dn-img-page.kakao.com/download/resource?kid=R6c6g/hyoXA932mI/AdzXV2kk8wDCqOMBzZAkY1&filename=o1',
    service: 'kakao',
    searchKeyword: '가드패스오손도손',
    genre: ['학원', '판타지'],
    day: 'sun',
  },
  {
    webtoonId: 2826,
    title: '빙의자를 위한 특혜',
    author: '구르, 이린비',
    des: '※사후 세계를 대비하세요! 죽기 직전에 받은 이상한 스팸문자. 죽은 줄 알고 눈떠보니 빙의심사국이다. 정말 사후 세계가 있다고? 책 속으로 빙의될 거라고? "특별히 선호하는 장르가 있으신가요?" 전생에 덕질로 모든 장르를 섭렵한 나. 다음 생은 귀염 뽀짝한 여자아이가 되어 무한한 사랑을 독차지하는 육아물을 희망했건만. 내가 빙의될 책은ㅡ 생존 난이도 S급, 고구마 가득한 무한회귀물 <세상을 구할 때까지 회귀>다. 거기에서 빙의될 캐릭터는ㅡ 주인공에게 갑질하는 망나니 귀족가ㅡ에서 갑질 당하는 평민 하인의 딸?! 하지만 죽기 직전에 가입한 <빙의생명보험 풀패키지>덕분에 특급 특혜를 얻게 되는데... 덕력에서 얻은 센스와, 보험 특혜와, 신의 편애와 총애로 고구마 가득한 S급 생존물에서 살아남는 이야기!',
    url: 'https://webtoon.kakao.com/content/%EB%B9%99%EC%9D%98%EC%9E%90%EB%A5%BC-%EC%9C%84%ED%95%9C-%ED%8A%B9%ED%98%9C/2826',
    img: '//dn-img-page.kakao.com/download/resource?kid=bFpcAU/hzVqEeoMAJ/0ckzUrOQSoPaT9fvEwKmX1&filename=o1',
    service: 'kakao',
    searchKeyword: '빙의자를위한특혜구르이린비',
    genre: ['로맨스', '판타지'],
    day: 'sun',
  },
  {
    webtoonId: 2957,
    title: '존재',
    author: '광진, 김경준',
    des: '언젠가는 떼를 짓는 개미, 언젠가는 홀로 큰 공룡이었다.수만 번의 윤회로 각기 다른 생명을 경험했던 한 존재의 마지막 생.지금껏 경험한 모든 생의 능력을 가진 인간으로 태어났다.왜 이런 능력을 갖게 됐을까.이자인은 드디어 깨달았다."난 인간을 멸종시키기 위해 존재하는 거야"',
    url: 'https://webtoon.kakao.com/content/%EC%A1%B4%EC%9E%AC/2957',
    img: '//dn-img-page.kakao.com/download/resource?kid=bzrngZ/hzCtesFxOO/dEshvHcxiOdM1zEWJw7bJ1&filename=o1',
    service: 'kakao',
    searchKeyword: '존재광진김경준',
    genre: ['판타지', '드라마'],
    day: 'sun',
  },
  {
    webtoonId: 1575,
    title: '슬프게도 이게 내 인생',
    author: '슬',
    des: '"벌어먹고 살아야 하는 현생은 너무 힘들어!"거친 현대사회에서 이리저리 치이며어떻게든 적응해보려는 어리바리 슬이와쉽지 않은 직장 생활에 약간 돌아버린 친구들의슬프지만 즐겁게 살려고 노력하는 이야기',
    url: 'https://webtoon.kakao.com/content/%EC%8A%AC%ED%94%84%EA%B2%8C%EB%8F%84-%EC%9D%B4%EA%B2%8C-%EB%82%B4-%EC%9D%B8%EC%83%9D/1575',
    img: '//dn-img-page.kakao.com/download/resource?kid=bZnhj3/hzp2mv6pRT/aVjQh7aDXprmmumMW4N8v1&filename=o1',
    service: 'kakao',
    searchKeyword: '슬프게도이게내인생슬',
    genre: ['코믹', '일상'],
    day: 'sun',
  },
  {
    webtoonId: 2852,
    title: '검술명가 막내아들',
    author: 'AZI, COBY(Contentslabblue), 이제원, 황제펭권',
    des: '세계 제일의 검술명가 룬칸델. 그곳에서 수치라 불리는 룬칸델 최악의 둔재 "진"가문에서 추방당한 그는 그림자의 신 "솔더렛"과의 계약을 통해 힘을 얻기 시작한다.하지만... 잠을 자던 도중 비참하게 살해당하고 마는데... .눈을 뜬 그는 자신이 과거로 거로 회귀했다는 사실을 깨닫는다.그는 자신을 죽음으로 몰고간 자들에게 복수를 다짐하고전생과는 다른 삶을 살 것을 맹세한다.',
    url: 'https://webtoon.kakao.com/content/%EA%B2%80%EC%88%A0%EB%AA%85%EA%B0%80-%EB%A7%89%EB%82%B4%EC%95%84%EB%93%A4/2852',
    img: '//dn-img-page.kakao.com/download/resource?kid=bKzthG/hzMT8bp1Ic/wN3bk5EEJamPrI1WiOuW10&filename=o1',
    service: 'kakao',
    searchKeyword: '검술명가막내아들AZICOBYContentslabblue이제원황제펭권',
    genre: ['액션', '무협'],
    day: 'sun',
  },
  {
    webtoonId: 3340,
    title: '소녀 가주가 되었습니다',
    author: '파도, 랄라, 단리한',
    des: '리아르 백작가의 장녀로 빙의했다가 소녀 가장이 되어 버린 아르셀.원작대로라면 친척들에게 가문의 모든 것을 빼앗기고 어린 동생과 함께 바닷가에서 얼어 죽게 된다.가문을 노리는 친척들로부터 어린 동생과 자신을 지키는 유일한 방법은동부 바다의 수호자라 알려졌지만, 사실은 해적 가문의 수장인 ‘가엘 폰 제나트’와 계약 결혼하는 것!“리아르가의 해역이 필요한 일을 하고 계시다는 걸 알아요.”“나랑 결혼해주세요.”로맨틱한 청혼은 아니었다. 다만 완벽한 거래였다.그런데...“조금만 더 나를 가까이 대해 주세요.”자꾸만 그의 다정함이 느껴진다.',
    url: 'https://webtoon.kakao.com/content/%EC%86%8C%EB%85%80-%EA%B0%80%EC%A3%BC%EA%B0%80-%EB%90%98%EC%97%88%EC%8A%B5%EB%8B%88%EB%8B%A4/3340',
    img: '//dn-img-page.kakao.com/download/resource?kid=N4iJu/hzXardlkWQ/v0vMswZ2rJAtOLnELrC261&filename=o1',
    service: 'kakao',
    searchKeyword: '소녀가주가되었습니다파도랄라단리한',
    genre: ['로맨스', '판타지'],
    day: 'sun',
  },
]

const addData = async (webtoon: IWebtoon) => {
  const docRef = await setDoc(doc(db, 'webtoon', webtoon.title), {
    webtoonId: webtoon.webtoonId,
    title: webtoon.title,
    author: webtoon.author,
    des: webtoon.des,
    url: webtoon.url,
    img: webtoon.img,
    service: webtoon.service,
    searchKeyword: webtoon.searchKeyword,
    genre: webtoon.genre,
    day: webtoon.day,
  })
}

WebtoonData.forEach((webtoon) => {
  // addData(webtoon)
})
